Issue Number,Issue Title,Issue Body
172,Wrong Logistic Loss,"In tensorflow/python/ops/nn.py, the logistic loss is described as

x - x \* z + log(1 + exp(-x))

but this is not what's commonly known as the logistic loss.
I see that you're trying to apply a trick here to avoid overflow, but it should be 

x - x \* z + log(exp(0 - (x - x \* z)) + exp(-x))

instead of what you have.

Of course, the correct version is now prone to underflow, so it would make most sense to add a native robust log-sum-exp function to tensorflow and then rely on that to avoid over- and underflow.
"
171,Tensorboard creates unecessary loops in graph,"I've followed the mnist expert tutorial and wanted to see the graph on the tensorboard. The dashboard looks great, except that in the graph unrelated nodes are grouped together, creating weird loops and making it harder to follow what's happening. Especially with Relu_1 & Relu_2, the merging of the arrows are quite confusing.

![screenshot tensorboard](https://cloud.githubusercontent.com/assets/725737/11115434/c009582e-892b-11e5-8d55-89666555b14e.png)

Code:

``` python
import input_data

mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

import tensorflow as tf


def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)


def bias_variable(shape):
    initial = tf.constant(0.1, shape=shape)
    return tf.Variable(initial)


def conv2d(x, W):
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')


def max_pool_2x2(x):
    return tf.nn.max_pool(x, ksize=[1, 2, 2, 1],
                          strides=[1, 2, 2, 1], padding='SAME')


sess = tf.InteractiveSession()

x = tf.placeholder(""float"", shape=[None, 784])
y_ = tf.placeholder(""float"", shape=[None, 10])

W_conv1 = weight_variable([5, 5, 1, 32])
b_conv1 = bias_variable([32])

x_image = tf.reshape(x, [-1, 28, 28, 1])

h_conv1 = tf.nn.relu(conv2d(x_image, W_conv1) + b_conv1)
h_pool1 = max_pool_2x2(h_conv1)

W_conv2 = weight_variable([5, 5, 32, 64])
b_conv2 = bias_variable([64])

h_conv2 = tf.nn.relu(conv2d(h_pool1, W_conv2) + b_conv2)
h_pool2 = max_pool_2x2(h_conv2)

W_fc1 = weight_variable([7 * 7 * 64, 1024])
b_fc1 = bias_variable([1024])

h_pool2_flat = tf.reshape(h_pool2, [-1, 7 * 7 * 64])
h_fc1 = tf.nn.relu(tf.matmul(h_pool2_flat, W_fc1) + b_fc1)

keep_prob = tf.placeholder(""float"")
h_fc1_drop = tf.nn.dropout(h_fc1, keep_prob)

W_fc2 = weight_variable([1024, 10])
b_fc2 = bias_variable([10])

y_conv = tf.nn.softmax(tf.matmul(h_fc1_drop, W_fc2) + b_fc2)

cross_entropy = -tf.reduce_sum(y_ * tf.log(y_conv))
train_step = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)
correct_prediction = tf.equal(tf.argmax(y_conv, 1), tf.argmax(y_, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, ""float""))


tf.scalar_summary('Training error', cross_entropy)
tf.scalar_summary('Training accuracy', accuracy)
tf.scalar_summary('sparsity', tf.nn.zero_fraction(h_fc1))

sess.run(tf.initialize_all_variables())


merged_summary_op = tf.merge_all_summaries()
print merged_summary_op
summary_writer = tf.train.SummaryWriter('/tmp/mnist_logs', sess.graph_def)

for i in range(20000):
    batch = mnist.train.next_batch(50)
    sess.run(train_step, feed_dict={x: batch[0], y_: batch[1], keep_prob: 0.5})
    if i % 100 == 0:
        train_accuracy = accuracy.eval(feed_dict={
            x: batch[0], y_: batch[1], keep_prob: 1.0})
        print ""step %d, training accuracy %g"" % (i, train_accuracy)
        summary_str = sess.run(merged_summary_op, feed_dict={x: batch[0], y_: batch[1], keep_prob: 0.5})
        summary_writer.add_summary(summary_str, i)



print ""test accuracy %g"" % accuracy.eval(feed_dict={
    x: mnist.test.images, y_: mnist.test.labels, keep_prob: 1.0})
```
"
170,Not a gzipped file,"When I get started with 'Train your first TensorFlow neural net model':
`$ python tensorflow/models/image/mnist/convolutional.py`

There is an error:

```
File ""tensorflow/models/image/mnist/convolutional.py"", line 59, in extract_data
    bytestream.read(16)
  File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py"", line 268, in read
    self._read(readsize)
  File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py"", line 303, in _read
    self._read_gzip_header()
  File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py"", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
```
"
169,Small typo in Deep MNIST Tutorial,"There is a small typo on the [Deep MNIST for Experts](http://tensorflow.org/tutorials/mnist/pros/index.md) page. It's the first sentence of the second paragraph under the Start TensorFlow InteractiveSession header.

> Here we instead use the convenience InteractiveSession class, ...

should maybe  be

> Here we instead use the convenient InteractiveSession class,...

or maybe

> Here we instead use the convenience of the InteractiveSession class, ...
"
168,tensor flow does not support operator.__truediv__,"tensorflow type does not support operation.**truediv** as in the basic example in https://tensorflow.googlesource.com/tensorflow/+/master/tensorflow/g3doc/tutorials/word2vec/word2vec_basic.py
In line 153,  ' normalized_embeddings = embeddings / norm'  will cause the attribute error as followed

""AttributeError: type object 'Tensor' has no attribute '**truediv**""

To solve the problem, we can replace this line as 'normalized_embeddings = tf.div(embeddings, norm)'
"
167,g3doc is not installed when using pip ,"Hi All,

At least under Mac OS X the following command:

pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl

will not install g3doc (and probably some other modules). 

Just a minor issue :)
"
166,Does TensorFlow support temporal convolution,"like [Torch does](https://github.com/torch/nn/blob/master/doc/convolution.md)? I assume not, hence asking here.

Temporal convolution is useful for encoding a sentence. I find it work better than RNN/LSTM.
"
165,in_top_k op does not work with int64 labels,"The `tf.nn.in_top_k` op does not work with `int64` labels. This is problematic when computing accuracy from a one-hot encoding of labels as the output of `argmax` is `int64`:

``` python
y = tf.placeholder(""float"")
yhat = tf.placeholder(""float"")
tf.nn.in_top_k(yhat, tf.argmax(y, 1), 1)
```

yields the error:

```
TypeError: Input 'targets' of 'InTopK' Op has type int64 that does not match expected type of int32.
```

The simple workaround is to cast the labels before calling the op:

```
tf.nn.in_top_k(y, tf.cast(tf.argmax(y_, 1), ""int32""), 1)
```

but it'd be nice if `int64` labels were supported out of the box.
"
164,Direct Native Code / LLVM IR generation / JIT Compilation / Staging / Incremental Computing,"If it possible to have a feature to bypass C++ and go directly to Native / LLVM IR
"
163,Published Roadmap,"Can you publish a road map to get an idea on the direction which project is going?
"
162,Any Roadmap Available?,"As stated on http://tensorflow.org,

> TensorFlow is not complete; it is intended to be built upon and extended.

I would therefore like to know if a roadmap exists.
"
161,Can't install tensorflow on OS X - problem with virtualenv,"I try to install tensorflow, but run into this message, what should I do?

Johans-MacBook-Pro:~ johanbjorck$ pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
Could not find an activated virtualenv (required).
Johans-MacBook-Pro:~ johanbjorck$ 
"
160,doc for install from source of pip+gpu missing --config=cuda and --use_gpu,"I was able to use GPU from python on AWS g2.2xlarge only after adding `--config=cuda` and `--use_gpu`
to the the instructions for creating a pip at http://tensorflow.org/get_started/os_setup.md#installing_from_sources

```
$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg --use_gpu
```
"
159,tensorflow binary image for ARM architecture,"Any chance that an ARM compatible tensorflow whl binary image is available for Linux? 
"
156,RuntimeError: Broken toolchain: cannot link a simple C program,"Trying to install on Ubuntu 14.04.03 using pip, i have this error

```
pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
```

```
RuntimeError: Broken toolchain: cannot link a simple C program
Command /usr/bin/python -c ""import setuptools, tokenize;__file__='/tmp/pip_build_root/numpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))"" install --record /tmp/pip-hnmAZh-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/numpy
Storing debug log for failure in /root/.pip/pip.log
```
"
153,Library not loaded: /usr/lib/libc++.1.dylib,"When trying to run an example, as given in the [instructions](http://tensorflow.org/get_started/os_setup.md#virtualenv_install), the command ""python tensorflow/models/image/mnist/convolutional.py"" does not work because that is not the proper path to convolutional.py.

If I use the proper path, I get this error:

```
 $ source bin/activate
(tensorflow) $ python lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py
Traceback (most recent call last):
  File ""lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py"", line 12, in <module>
    import tensorflow.python.platform
  File ""/Users/munafo/devt/tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py"", line 4, in <module>
    from tensorflow.python import *
  File ""/Users/munafo/devt/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py"", line 22, in <module>
    from tensorflow.python.client.client_lib import *
  File ""/Users/munafo/devt/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/client_lib.py"", line 35, in <module>
    from tensorflow.python.client.session import InteractiveSession
  File ""/Users/munafo/devt/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py"", line 11, in <module>
    from tensorflow.python import pywrap_tensorflow as tf_session
  File ""/Users/munafo/devt/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py"", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File ""/Users/munafo/devt/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py"", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: dlopen(/Users/munafo/devt/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so, 2): Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /Users/munafo/devt/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found
(tensorflow) $ 
```

I have a complete index of all files on my machine, and there is no ""libc++.1.dylib"" anywhere. I do have a ""/usr/lib/libstdc++.6.dylib"".

MacOS 10.6.8, Python 2.7.3, virtualenv 1.7.1.2
"
152,Segmentation fault when GPUs are already used,"When I set the nvidia driver in exclusive mode and one of the GPU is already used by another process, I get a segmentation fault:

```
$ python -c ""import tensorflow as tf;tf.InteractiveSession()""
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 12
Segmentation fault (core dumped)
```

If I limit the visible GPUs to only GPUs that have nothing running on them, it don't segfault:

```
$CUDA_VISIBLE_DEVICES=1 python -c ""import tensorflow as tf;tf.InteractiveSession()""
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 12
I tensorflow/core/common_runtime/gpu/gpu_init.cc:88] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:09:00.0
Total memory: 12.00GiB
Free memory: 11.87GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:112] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:122] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:643] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:09:00.0)
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:47] Setting region size to 12105628263
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 12
```

Here is my output of nvidia-smi:

```
$ nvidia-smi 
Wed Nov 11 16:48:27 2015       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.39     Driver Version: 352.39         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 750     Off  | 0000:05:00.0      On |                  N/A |
| N/A   48C    P8     0W /  38W |     25MiB /  2047MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 0000:06:00.0     Off |                  N/A |
| 42%   82C    P2   127W / 250W |    262MiB / 12287MiB |     39%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 0000:09:00.0     Off |                  N/A |
| 22%   46C    P8    17W / 250W |     23MiB / 12287MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 0000:0A:00.0     Off |                  N/A |
| 22%   37C    P8    15W / 250W |    361MiB / 12287MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1171    G   /usr/bin/X                                      17MiB |
|    1     32740    C   python                                         209MiB |
|    3      9429    C   python                                         336MiB |
+-----------------------------------------------------------------------------+

```

I suppose that in the code that check the available GPUs, it don't handle correctly a case when one of the GPUs can't be used.
"
151,Typo in reshape documentation,"Small typo at 
http://tensorflow.org/api_docs/python/array_ops.md#AUTOGENERATED-shapes-and-shaping 
Under the reshape example it says: 

> tensor 't' is [[[1, 1], [2, 2]]
>                [[3, 3], [4, 4]]]
> tensor 't' has shape [2, 2]

But I think t initially has the shape [2, 2, 2] not [2, 2].
"
150,Is there 3D ConvNets support ? ,"(Is there) **or** (will there be) a **3D ConvNets** support in **tensorflow** ?  
Which helps for spatiotemporal features. 
"
149,Official Tensorflow Docker Image,"Hello Tensorflow Community,

I just wanted to kick start a discussions on creating an official docker image for Tensorflow. So going in line with creating common framework for machine learning related researchers and developers to rally around, and given the onslaught on software containers, I think creating a common Tensorflow image would also help in the same regard. 

I'd normally make a more detailed proposal as I did for a cuda docker image [here](https://devtalk.nvidia.com/default/topic/858201/official-docker-image-for-cuda-/?), but my goal right now is just to facilitate a discussion. I know there are many technical issues thanks in part to heavy use of GPUs and driver dependencies, but it looks like Nvidia is making some progress on that front: [NVIDIA/nvidia-docker](https://github.com/NVIDIA/nvidia-docker).

So if you like the idea or have some ideas/drafts, please chime in. 
"
148,"Wrong link in the ""common problems"" docs","On the ""Getting started page"" in the following part:

```
Common Problems
GPU-related issues

If you encounter the following when trying to run a TensorFlow program:

ImportError: libcudart.so.7.0: cannot open shared object file: No such file or directory

Make sure you followed the the GPU installation instructions.
```

The last word ""instructions"" leads to http://www.tensorflow.org/#install_cuda, however the main page it leads to does not have an anchor ""install_cuda"", so it just ends up leading to the top of main page.

Presumably, the correct link is http://www.tensorflow.org/get_started/os_setup.md#install_cuda
"
147,add multiple-machine support,"Many projects require more resources than are available in a single machine. **Does the current opensource release of Tensorflow support processing that spans multiple-machines?**

I ask because the main webpage (says single machine) seems to conflict[1] with the Tensorflow whitepaper pdf (says multiple machines).

If the current opensource tensorflow does not support multiple-machine execution but the closed-sourced version does. **Is there any plan to release an opensource version that supports multiple machines? Is there an approximate timeframe?**

[1]
- The [tensorflow.org main webpage](http://tensorflow.org/) says ""This open source release supports single machines"". Also the [Resources/FAQ says ""single computer""](http://tensorflow.org/resources/faq.md).
- But then when you [read the Tensorflow whitepaper](http://download.tensorflow.org/paper/whitepaper2015.pdf), the whitepaper indicates in many places that Tensorflow can run across multiple machines. See these quotes from the whitepaper:
  - ""large-scale  distributed  systems  of  hundreds of machines"" and ""using
    many  hundreds  of  machines""
  - "" extends  it with  support  for  an environment where the client, the master, and the workers can all be in different processes on different machines""
  - ""use remote communication mechanisms such as TCP or RDMA to move data across machine boundaries""
"
146,Wrong multiplication in MNIST beginner tutorial,"(Not sure if this is the right place to report a problem with [this tutorial](http://tensorflow.org/tutorials/mnist/beginners/index.md).)

I believe that the explanation of matrix multiplication in [this image](http://api.tensorflow.org/system/image/body/1707/softmax-regression-scalarequation.png) is wrong.

It should be W_1,1 x_1 + W_1,2 x_2 + W_1,3 x_3... (i.e., x should increase per row, not per column).
"
145,"unable to install -Inside the virtualenv, install TensorFlow:","everytime i execute the line

(tensorflow)$ pip install --upgrade <$url_to_binary.whl>

I get below errors. Experts pls help. 

Hemanths-MBP:tensorflow hemanthreganti$ (tensorflow)$ pip install --upgrade <$url_to_binary.whl>
-bash: syntax error near unexpected token `$'
Hemanths-MBP:tensorflow hemanthreganti$  pip install --upgrade <$url_to_binary.whl>
-bash: syntax error near unexpected token`newline'
Hemanths-MBP:tensorflow hemanthreganti$ pip install --upgrade <$url_to_binary.whl>
-bash: syntax error near unexpected token `newline'
Hemanths-MBP:tensorflow hemanthreganti$  source bin/activate 
(tensorflow)Hemanths-MBP:tensorflow hemanthreganti$ pip install --upgrade <$url_to_binary.whl>
-bash: syntax error near unexpected token`newline'
(tensorflow)Hemanths-MBP:tensorflow hemanthreganti$ (tensorflow)$ pip install --upgrade <$url_to_binary.whl>
-bash: syntax error near unexpected token `$'
(tensorflow)Hemanths-MBP:tensorflow hemanthreganti$ (tensorflow)$ python tensorflow/models/image/mnist/convolutional.py
-bash: syntax error near unexpected token`$'
(tensorflow)Hemanths-MBP:tensorflow hemanthreganti$ python tensorflow/models/image/mnist/convolutional.py
python: can't open file 'tensorflow/models/image/mnist/convolutional.py': [Errno 2] No such file or directory
(tensorflow)Hemanths-MBP:tensorflow hemanthreganti$ 
"
144,tutorial GPU issue,"Hi guys,
I suppose that you've got an error in tutorial, section ""Create the pip package and install"" ([link](http://www.tensorflow.org/get_started/os_setup.md#installing_from_sources)):

1) this command should create pip package:
$ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package 

In order to use GPU in training you need to specify --config=cuda:
$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package 
"
143,Truncated backdrop with max pooling over time,"It seems like the way truncated backprop is done, at least in the tutorial on RNNs, is to 
- set up the data in batches where the time dimension is capped at the max `num_steps` 
- run forward/backward passes making sure to use the correct initial state (e.g final state of the previous batch if was part of the same observation but prior in time or the true initial state if the current batch starts at true `t=0`)

This works fine if each hidden state contributes directly to the loss but this approach fails if you want to do something like max pooling across time.  You can carry around the current max (like the correct initial state for truncated backprop) but it seems like the gradient won't flow from the loss, to the max'd elements.  

To summarize, truncated backprop won't work in situations when a given hidden state at time `t`'s contribution to the loss is unknown without knowing the hidden states for all `t`.  

Would love to be wrong.  
"
142,TF not compatible with AWS GPU instances?,"It seems like Google Compute Engine doesn't even have gpu instances, and AWS GPU instance isn't supported because it requires >= 3.5 cuda compute capability.  Is this correct?
"
141,typo in decaying the learning rate example,"From example in [docs](http://tensorflow.org/api_docs/python/train.md#decaying_the_learning_rate):

> learning_rate = tf.exponential_decay(starter_learning_rate, global_step,
>                                      100000, 0.96, staircase=True)

should match function definiton above `tf.train.exponential_decay`.
"
140,Questions about using LSTM ,"Hi. I am a newbie on TensorFlow, just like most of the others here.
I was trying to use the LSTM modules, and some questions arose.
1. How can I cope with non-fixed length of sequences? For example, the length of longest sentence in each batch is different, but in RNN tutorial, it does like 

for i in range(len(num_steps)):
    # The value of state is updated after processing each batch of words.
    output, state = lstm(words[:, i], state)

....

when this ""num_steps"" is not set, what kind of value or variable can I use?
1. How can I use mask in LSTM? within a batch, all the sentences have different length, so it is essential to mask the lstm results according to the length of each sentence. I don't think there is masking function inside TensorFlor LSTM module. What options do I have?

Sorry for bothering you, and thank you for making public this great project.

-Taeksoo
"
139,unable to use nn.moments when the dimension of the axis is None,"calling `nn.moments` with an axis of dimension `None` produces this error:

```
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn.py"", line 536, in moments
    divisor *= x.get_shape()[d].value
TypeError: unsupported operand type(s) for *=: 'float' and 'NoneType'
```

is it possible for the `nn.moments` implementation to use the inferred dimension in it's calculation?
"
138,Out of Memory in mnist?,"ubuntu@slave1:/media/slave1temp/tensorflow_full$ python tensorflow/tensorflow/models/image/mnist/convolutional.py
Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 8
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:888] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:88] Found device 0 with properties: 
name: GeForce GTX 750 Ti
major: 5 minor: 0 memoryClockRate (GHz) 1.189
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.96GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:112] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:122] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:643] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 750 Ti, pci bus id: 0000:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:47] Setting region size to 1896685568
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 8
Initialized!
Epoch 0.00
Minibatch loss: 12.054, learning rate: 0.010000
Minibatch error: 90.6%
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 256 (256B) Pool: chunks: 64 free: 35 cumulative malloc: 93 cumulative freed: 64
Number of chunks: 64, in_use chunks: 29
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 2048 (2.0KiB) Pool: chunks: 8 free: 4 cumulative malloc: 7 cumulative freed: 3
Number of chunks: 8, in_use chunks: 4
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 4096 (4.0KiB) Pool: chunks: 16 free: 13 cumulative malloc: 18 cumulative freed: 15
Number of chunks: 16, in_use chunks: 3
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 32768 (32.0KiB) Pool: chunks: 8 free: 5 cumulative malloc: 9 cumulative freed: 6
Number of chunks: 8, in_use chunks: 3
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 139264 (136.0KiB) Pool: chunks: 15 free: 15 cumulative malloc: 16 cumulative freed: 16
Number of chunks: 15, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 212992 (208.0KiB) Pool: chunks: 12 free: 9 cumulative malloc: 14 cumulative freed: 11
Number of chunks: 12, in_use chunks: 3
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 278528 (272.0KiB) Pool: chunks: 1 free: 1 cumulative malloc: 1 cumulative freed: 1
Number of chunks: 1, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 851968 (832.0KiB) Pool: chunks: 4 free: 4 cumulative malloc: 4 cumulative freed: 4
Number of chunks: 4, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 1703936 (1.62MiB) Pool: chunks: 6 free: 6 cumulative malloc: 6 cumulative freed: 6
Number of chunks: 6, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 2883584 (2.75MiB) Pool: chunks: 1 free: 1 cumulative malloc: 1 cumulative freed: 1
Number of chunks: 1, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 3407872 (3.25MiB) Pool: chunks: 8 free: 8 cumulative malloc: 9 cumulative freed: 9
Number of chunks: 8, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 6815744 (6.50MiB) Pool: chunks: 12 free: 9 cumulative malloc: 18 cumulative freed: 15
Number of chunks: 12, in_use chunks: 3
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 15728640 (15.00MiB) Pool: chunks: 1 free: 0 cumulative malloc: 1 cumulative freed: 0
Number of chunks: 1, in_use chunks: 1
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 20971520 (20.00MiB) Pool: chunks: 1 free: 1 cumulative malloc: 1 cumulative freed: 1
Number of chunks: 1, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 125829120 (120.00MiB) Pool: chunks: 1 free: 0 cumulative malloc: 1 cumulative freed: 0
Number of chunks: 1, in_use chunks: 1
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 251658240 (240.00MiB) Pool: chunks: 0 free: 0 cumulative malloc: 0 cumulative freed: 0
Number of chunks: 0, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 503316480 (480.00MiB) Pool: chunks: 3 free: 3 cumulative malloc: 3 cumulative freed: 3
Number of chunks: 3, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:345] Aggregate Region Memory: 1896685568 (1.77GiB)
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:347] Aggregate Chunk Memory: 1803329536 (1.68GiB)
W tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:89] Out of GPU memory, see memory state dump above
W tensorflow/core/kernels/conv_ops.cc:162] Resource exhausted: OOM when allocating tensor with shapedim { size: 5000 } dim { size: 14 } dim { size: 14 } dim { size: 64 }
W tensorflow/core/common_runtime/executor.cc:1027] 0x57b6090 Compute status: Resource exhausted: OOM when allocating tensor with shapedim { size: 5000 } dim { size: 14 } dim { size: 14 } dim { size: 64 }
     [[Node: Conv2D_3 = Conv2D[T=DT_FLOAT, padding=""SAME"", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device=""/job:localhost/replica:0/task:0/gpu:0""](MaxPool_2, Variable_2)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x50bc640 Compute status: Resource exhausted: OOM when allocating tensor with shapedim { size: 5000 } dim { size: 14 } dim { size: 14 } dim { size: 64 }
     [[Node: Conv2D_3 = Conv2D[T=DT_FLOAT, padding=""SAME"", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device=""/job:localhost/replica:0/task:0/gpu:0""](MaxPool_2, Variable_2)]]
     [[Node: Softmax_1/_45 = _Recv[client_terminated=false, recv_device=""/job:localhost/replica:0/task:0/cpu:0"", send_device=""/job:localhost/replica:0/task:0/gpu:0"", send_device_incarnation=1, tensor_name=""edge_735_Softmax_1"", tensor_type=DT_FLOAT, _device=""/job:localhost/replica:0/task:0/cpu:0""]()]]
Traceback (most recent call last):
  File ""tensorflow/tensorflow/models/image/mnist/convolutional.py"", line 270, in <module>
    tf.app.run()
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py"", line 11, in run
    sys.exit(main(sys.argv))
  File ""tensorflow/tensorflow/models/image/mnist/convolutional.py"", line 258, in main
    validation_prediction.eval(), validation_labels)
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py"", line 405, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py"", line 2728, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py"", line 345, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py"", line 419, in _do_run
    e.code)
tensorflow.python.framework.errors.ResourceExhaustedError: OOM when allocating tensor with shapedim { size: 5000 } dim { size: 14 } dim { size: 14 } dim { size: 64 }
     [[Node: Conv2D_3 = Conv2D[T=DT_FLOAT, padding=""SAME"", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device=""/job:localhost/replica:0/task:0/gpu:0""](MaxPool_2, Variable_2)]]
     [[Node: Softmax_1/_45 = _Recv[client_terminated=false, recv_device=""/job:localhost/replica:0/task:0/cpu:0"", send_device=""/job:localhost/replica:0/task:0/gpu:0"", send_device_incarnation=1, tensor_name=""edge_735_Softmax_1"", tensor_type=DT_FLOAT, _device=""/job:localhost/replica:0/task:0/cpu:0""]()]]
Caused by op u'Conv2D_3', defined at:
  File ""tensorflow/tensorflow/models/image/mnist/convolutional.py"", line 270, in <module>
    tf.app.run()
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py"", line 11, in run
    sys.exit(main(sys.argv))
  File ""tensorflow/tensorflow/models/image/mnist/convolutional.py"", line 229, in main
    validation_prediction = tf.nn.softmax(model(validation_data_node))
  File ""tensorflow/tensorflow/models/image/mnist/convolutional.py"", line 179, in model
    padding='SAME')
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py"", line 207, in conv2d
    use_cudnn_on_gpu=use_cudnn_on_gpu, name=name)
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py"", line 633, in apply_op
    op_def=op_def)
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py"", line 1710, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py"", line 988, in __init__
    self._traceback = _extract_stack()

ubuntu@slave1:/media/slave1temp/tensorflow_full$ 
"
137,bazel always re-downloaded the dependency libraries,"I use `bazel build -c opt //tensorflow/tools/pip_package:build_pip_package` to build the package. But it always re-downloaded the dependency git repositories. 

Hi, I'm not familiar with `bazel`. Is it reasonable?
"
136,ResourceExhaustedError in CNN/MNIST example (with GPU),"(I'm using GPU(GTX 980) with CUDA-7.0&cuDNNv2, on Ubuntu 14.04)
I have gone through MNIST tutorial: http://tensorflow.org/tutorials/mnist/pros/index.md

Everything was going well except for the last two lines:

``` python
print ""test accuracy %g""%accuracy.eval(feed_dict={
    x: mnist.test.images, y_: mnist.test.labels, keep_prob: 1.0})
```

Executing these lines, I got an error: 

``` python
ResourceExhaustedError: OOM when allocating tensor with shapedim { size: 10000 } dim { size: 18 } dim { size: 18 } dim { size: 32 }
```

I think basic reason for this error is that test data can not be allocated to GPU device.
Is this a bug or not? Are there good way to avoid this issue?
"
135,osx 10.11 installation issues,"Trying to install it with `pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.wh`. Same issue if doing it with virutalenv. 

Exception:
Traceback (most recent call last):
  File ""/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/basecommand.py"", line 211, in main
    status = self.run(options, args)
  File ""/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/commands/install.py"", line 305, in run
    wb.build(autobuilding=True)
  File ""/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/wheel.py"", line 705, in build
    self.requirement_set.prepare_files(self.finder)
  File ""/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/req/req_set.py"", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File ""/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/req/req_set.py"", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File ""/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/req/req_set.py"", line 491, in _prepare_file
    session=self.session)
  File ""/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/download.py"", line 825, in unpack_url
    session,
  File ""/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/download.py"", line 673, in unpack_http_url
    from_path, content_type = _download_http_url(link, session, temp_dir)
  File ""/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/download.py"", line 857, in _download_http_url
    stream=True,
  File ""/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py"", line 477, in get
    return self.request('GET', url, *_kwargs)
  File ""/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/download.py"", line 373, in request
    return super(PipSession, self).request(method, url, *args, *_kwargs)
  File ""/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py"", line 465, in request
    resp = self.send(prep, *_send_kwargs)
  File ""/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py"", line 573, in send
    r = adapter.send(request, *_kwargs)
  File ""/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py"", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File ""/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py"", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

 I've installed openssl (1.0.2d) through homebrew.

Tried with bazel: `bazel build -c opt //tensorflow/tools/pip_package:build_pip_package` and the following error pops up:
`ERROR: no such package 'tensorflow/tools/pip_package': BUILD file not found on package path.`
I've got tensorflow running with docker but I want it in the host machine.
"
134,Linux installation issue for GPU-enabled version,"Hi,

I ran the command ""$ pip install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl"" and I got:

```
Downloading/unpacking https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
  Downloading tensorflow-0.5.0-cp27-none-linux_x86_64.whl (50.5Mb): 50.5Mb downloaded
  Running setup.py egg_info for package from https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
    Traceback (most recent call last):
      File ""<string>"", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-o6Tpui-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File ""<string>"", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip-o6Tpui-build/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/pip-o6Tpui-build
Storing complete log in /home/shubhanshu/.pip/pip.log
Traceback (most recent call last):
  File ""/usr/bin/pip"", line 9, in <module>
    load_entry_point('pip==1.1', 'console_scripts', 'pip-2.7')()
  File ""/usr/lib/python2.7/dist-packages/pip/__init__.py"", line 116, in main
    return command.main(args[1:], options)
  File ""/usr/lib/python2.7/dist-packages/pip/basecommand.py"", line 141, in main
    log_fp = open_logfile(log_fn, 'w')
  File ""/usr/lib/python2.7/dist-packages/pip/basecommand.py"", line 168, in open_logfile
    log_fp = open(filename, mode)
IOError: [Errno 13] Permission denied: '/home/shubhanshu/.pip/pip.log'
```

Any directions, how to proceed ahead?
"
133,Linux installation problem with VirtualEnv,"I'm using virtual-env to install tensorflow. I've successfully created a virtual-env and when trying to install tensorflow using pip, i'm getting this error.
Any suggestions ?? Thanks.

```
Unpacking /home/ayan/Desktop/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
  Running setup.py egg_info for package from file:///home/ayan/Desktop/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
    Traceback (most recent call last):
      File ""<string>"", line 16, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-ULRUTP-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  File ""<string>"", line 16, in <module>
IOError: [Errno 2] No such file or directory: '/tmp/pip-ULRUTP-build/setup.py'
----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/pip-ULRUTP-build
Storing complete log in /home/ayan/.pip/pip.log
```
"
132,Communicating channels: gitter.im + discourse,"If we're in for the openess and effectiveness of the whole thing...

(1) Why not using gitter.im ?

I also believe we should have a discourse forums, which I'm more than willing to help / set up if you really need (just can't pay for it or move people from the mailing list without being official).

(2) Yes, discourse would be a **perfect** replacement for the mailing list **and** to this Issue tracker. :)
"
131,CUDA 7.0 is hard-coded in `configure` script for Linux,"I am running Ubuntu 15.04 with CUDA 7.5 installed. However, CUDA 7.0 is hard-coded in the `configure` script, and I am unable to configure to use CUDA 7.5:

```
❯❯❯ ./configure
Do you wish to build TensorFlow with GPU support? [y/n] y
GPU support will be enabled for TensorFlow

Please specify the location where CUDA 7.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
Invalid path to CUDA 7.0 toolkit. /usr/local/cuda/lib64/libcudart.so.7.0 cannot be found
```

This is because CUDA 7.5's libraries have the `.7.5` suffix rather than `.7.0`:

```
❯❯❯ ls -l /usr/local/cuda/lib64/libcudart.so*
lrwxrwxrwx 1 root root     16 Aug 15 08:55 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Aug 15 08:55 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 383336 Aug 15 08:55 /usr/local/cuda/lib64/libcudart.so.7.5.18
```
"
130,Use Bazel 0.1.1,"Currently, the [TensorFlow Getting Started](http://tensorflow.org/get_started/os_setup.md#installing_from_sources) doc recommends using Bazel 0.1.0. This is a pretty old release, and a number of bugs, such as bazelbuild/bazel#586, has been fixed since then.

This is a tracking bug to switch to a newer version of Bazel. I believe we are in the process of cutting a new release. I will ping this bug once we are ready to update the docs to recommend using a newer Bazel release.

Related: https://github.com/tensorflow/tensorflow/issues/129
"
129,Update docs to instruct to use Bazel 0.1.1 installer,"I noticed that the [TensorFlow Getting Started](http://tensorflow.org/get_started/os_setup.md#installing_from_sources) doc says to build Bazel 0.1.0 from source. It would be easier for users to use the Bazel installer to install Bazel instead as documented on the [Installing Bazel](http://bazel.io/docs/install.html) docs. The installers are available on the [Bazel releases](https://github.com/bazelbuild/bazel/releases) page.

Related: https://github.com/tensorflow/tensorflow/issues/130
"
128,Lots of C++ compile-time warnings,"I noticed a large number of compile-time warnings while compiling TensorFlow on Ubuntu 15.04.

I am building without GPU support using Bazel 0.1.1 (to work around bazelbuild/bazel#586) with the following command: `bazel build //tensorflow/cc:tutorials_example_trainer`

Many of the errors look like the following:

```
INFO: From Compiling tensorflow/cc/ops/nn_grad.cc:                                                                                                                                                                                                                                                                 [142/18386]
In file included from ./tensorflow/core/framework/op.h:10:0,
                 from ./tensorflow/core/framework/function.h:10,
                 from tensorflow/cc/ops/nn_grad.cc:1:
./tensorflow/core/lib/strings/str_util.h: In instantiation of 'std::vector<std::basic_string<char> > tensorflow::str_util::Split(tensorflow::StringPiece, char, Predicate) [with Predicate = tensorflow::str_util::AllowEmpty]':
./tensorflow/core/lib/strings/str_util.h:125:41:   required from here
./tensorflow/core/lib/strings/str_util.h:133:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < text.size() + 1; i++) {
                       ^
./tensorflow/core/lib/strings/str_util.h:134:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if ((i == text.size()) || (text[i] == delim)) {
              ^
INFO: From Compiling tensorflow/cc/ops/const_op.cc:
In file included from ./tensorflow/core/framework/op.h:10:0,
                 from ./tensorflow/core/graph/graph_def_builder.h:6,
                 from ./tensorflow/cc/ops/const_op.h:5,
                 from tensorflow/cc/ops/const_op.cc:1:
./tensorflow/core/lib/strings/str_util.h: In instantiation of 'std::vector<std::basic_string<char> > tensorflow::str_util::Split(tensorflow::StringPiece, char, Predicate) [with Predicate = tensorflow::str_util::AllowEmpty]':
./tensorflow/core/lib/strings/str_util.h:125:41:   required from here
./tensorflow/core/lib/strings/str_util.h:133:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < text.size() + 1; i++) {
                       ^
./tensorflow/core/lib/strings/str_util.h:134:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if ((i == text.size()) || (text[i] == delim)) {
              ^
In file included from ./tensorflow/core/framework/attr_value_util.h:7:0,
                 from ./tensorflow/core/framework/node_def_builder.h:5,
                 from ./tensorflow/core/graph/node_builder.h:5,
                 from ./tensorflow/core/graph/graph_def_builder.h:8,
                 from ./tensorflow/cc/ops/const_op.h:5,
                 from tensorflow/cc/ops/const_op.cc:1:
./tensorflow/core/public/tensor.h: In instantiation of 'typename tensorflow::TTypes<T, NDIMS>::Tensor tensorflow::Tensor::shaped(tensorflow::gtl::ArraySlice<long long int>) [with T = float; long unsigned int NDIMS = 1ul; typename tensorflow::TTypes<T, NDIMS>::Tensor = Eigen::TensorMap<Eigen::Tensor<float, 1ul, 1, lon
g int>, 1>]':
./tensorflow/core/public/tensor.h:190:40:   required from 'typename tensorflow::TTypes<T>::Flat tensorflow::Tensor::flat() [with T = float; typename tensorflow::TTypes<T>::Flat = Eigen::TensorMap<Eigen::Tensor<float, 1ul, 1, long int>, 1>]'
tensorflow/cc/ops/const_op.cc:63:1:   required from here
./tensorflow/core/public/tensor.h:411:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int d = 0; d < NDIMS; d++) {
                     ^
./tensorflow/core/public/tensor.h: In instantiation of 'typename tensorflow::TTypes<T, NDIMS>::Tensor tensorflow::Tensor::shaped(tensorflow::gtl::ArraySlice<long long int>) [with T = double; long unsigned int NDIMS = 1ul; typename tensorflow::TTypes<T, NDIMS>::Tensor = Eigen::TensorMap<Eigen::Tensor<double, 1ul, 1, l
ong int>, 1>]':
./tensorflow/core/public/tensor.h:190:40:   required from 'typename tensorflow::TTypes<T>::Flat tensorflow::Tensor::flat() [with T = double; typename tensorflow::TTypes<T>::Flat = Eigen::TensorMap<Eigen::Tensor<double, 1ul, 1, long int>, 1>]'
tensorflow/cc/ops/const_op.cc:64:1:   required from here
./tensorflow/core/public/tensor.h:411:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
./tensorflow/core/public/tensor.h: In instantiation of 'typename tensorflow::TTypes<T, NDIMS>::Tensor tensorflow::Tensor::shaped(tensorflow::gtl::ArraySlice<long long int>) [with T = int; long unsigned int NDIMS = 1ul; typename tensorflow::TTypes<T, NDIMS>::Tensor = Eigen::TensorMap<Eigen::Tensor<int, 1ul, 1, long in
t>, 1>]':
./tensorflow/core/public/tensor.h:190:40:   required from 'typename tensorflow::TTypes<T>::Flat tensorflow::Tensor::flat() [with T = int; typename tensorflow::TTypes<T>::Flat = Eigen::TensorMap<Eigen::Tensor<int, 1ul, 1, long int>, 1>]'
tensorflow/cc/ops/const_op.cc:65:1:   required from here
./tensorflow/core/public/tensor.h:411:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
./tensorflow/core/public/tensor.h: In instantiation of 'typename tensorflow::TTypes<T, NDIMS>::Tensor tensorflow::Tensor::shaped(tensorflow::gtl::ArraySlice<long long int>) [with T = unsigned char; long unsigned int NDIMS = 1ul; typename tensorflow::TTypes<T, NDIMS>::Tensor = Eigen::TensorMap<Eigen::Tensor<unsigned c
har, 1ul, 1, long int>, 1>]':
./tensorflow/core/public/tensor.h:190:40:   required from 'typename tensorflow::TTypes<T>::Flat tensorflow::Tensor::flat() [with T = unsigned char; typename tensorflow::TTypes<T>::Flat = Eigen::TensorMap<Eigen::Tensor<unsigned char, 1ul, 1, long int>, 1>]'
tensorflow/cc/ops/const_op.cc:66:1:   required from here
./tensorflow/core/public/tensor.h:411:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
./tensorflow/core/public/tensor.h: In instantiation of 'typename tensorflow::TTypes<T, NDIMS>::Tensor tensorflow::Tensor::shaped(tensorflow::gtl::ArraySlice<long long int>) [with T = short int; long unsigned int NDIMS = 1ul; typename tensorflow::TTypes<T, NDIMS>::Tensor = Eigen::TensorMap<Eigen::Tensor<short int, 1ul
, 1, long int>, 1>]':
./tensorflow/core/public/tensor.h:190:40:   required from 'typename tensorflow::TTypes<T>::Flat tensorflow::Tensor::flat() [with T = short int; typename tensorflow::TTypes<T>::Flat = Eigen::TensorMap<Eigen::Tensor<short int, 1ul, 1, long int>, 1>]'
tensorflow/cc/ops/const_op.cc:67:1:   required from here
./tensorflow/core/public/tensor.h:411:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
./tensorflow/core/public/tensor.h: In instantiation of 'typename tensorflow::TTypes<T, NDIMS>::Tensor tensorflow::Tensor::shaped(tensorflow::gtl::ArraySlice<long long int>) [with T = signed char; long unsigned int NDIMS = 1ul; typename tensorflow::TTypes<T, NDIMS>::Tensor = Eigen::TensorMap<Eigen::Tensor<signed char,
 1ul, 1, long int>, 1>]':
./tensorflow/core/public/tensor.h:190:40:   required from 'typename tensorflow::TTypes<T>::Flat tensorflow::Tensor::flat() [with T = signed char; typename tensorflow::TTypes<T>::Flat = Eigen::TensorMap<Eigen::Tensor<signed char, 1ul, 1, long int>, 1>]'
tensorflow/cc/ops/const_op.cc:68:1:   required from here
./tensorflow/core/public/tensor.h:411:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
./tensorflow/core/public/tensor.h: In instantiation of 'typename tensorflow::TTypes<T, NDIMS>::Tensor tensorflow::Tensor::shaped(tensorflow::gtl::ArraySlice<long long int>) [with T = long long int; long unsigned int NDIMS = 1ul; typename tensorflow::TTypes<T, NDIMS>::Tensor = Eigen::TensorMap<Eigen::Tensor<long long
int, 1ul, 1, long int>, 1>]':
./tensorflow/core/public/tensor.h:190:40:   required from 'typename tensorflow::TTypes<T>::Flat tensorflow::Tensor::flat() [with T = long long int; typename tensorflow::TTypes<T>::Flat = Eigen::TensorMap<Eigen::Tensor<long long int, 1ul, 1, long int>, 1>]'
tensorflow/cc/ops/const_op.cc:69:1:   required from here
./tensorflow/core/public/tensor.h:411:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
./tensorflow/core/public/tensor.h: In instantiation of 'typename tensorflow::TTypes<T, NDIMS>::Tensor tensorflow::Tensor::shaped(tensorflow::gtl::ArraySlice<long long int>) [with T = bool; long unsigned int NDIMS = 1ul; typename tensorflow::TTypes<T, NDIMS>::Tensor = Eigen::TensorMap<Eigen::Tensor<bool, 1ul, 1, long
int>, 1>]':
./tensorflow/core/public/tensor.h:190:40:   required from 'typename tensorflow::TTypes<T>::Flat tensorflow::Tensor::flat() [with T = bool; typename tensorflow::TTypes<T>::Flat = Eigen::TensorMap<Eigen::Tensor<bool, 1ul, 1, long int>, 1>]'
tensorflow/cc/ops/const_op.cc:70:1:   required from here
./tensorflow/core/public/tensor.h:411:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
./tensorflow/core/public/tensor.h: In instantiation of 'typename tensorflow::TTypes<T, NDIMS>::Tensor tensorflow::Tensor::shaped(tensorflow::gtl::ArraySlice<long long int>) [with T = std::complex<float>; long unsigned int NDIMS = 1ul; typename tensorflow::TTypes<T, NDIMS>::Tensor = Eigen::TensorMap<Eigen::Tensor<std:
:complex<float>, 1ul, 1, long int>, 1>]':
./tensorflow/core/public/tensor.h:190:40:   required from 'typename tensorflow::TTypes<T>::Flat tensorflow::Tensor::flat() [with T = std::complex<float>; typename tensorflow::TTypes<T>::Flat = Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 1ul, 1, long int>, 1>]'
tensorflow/cc/ops/const_op.cc:72:1:   required from here
./tensorflow/core/public/tensor.h:411:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
./tensorflow/core/public/tensor.h: In instantiation of 'typename tensorflow::TTypes<T, NDIMS>::Tensor tensorflow::Tensor::shaped(tensorflow::gtl::ArraySlice<long long int>) [with T = std::basic_string<char>; long unsigned int NDIMS = 1ul; typename tensorflow::TTypes<T, NDIMS>::Tensor = Eigen::TensorMap<Eigen::Tensor<
std::basic_string<char>, 1ul, 1, long int>, 1>]':
./tensorflow/core/public/tensor.h:190:40:   required from 'typename tensorflow::TTypes<T>::Flat tensorflow::Tensor::flat() [with T = std::basic_string<char>; typename tensorflow::TTypes<T>::Flat = Eigen::TensorMap<Eigen::Tensor<std::basic_string<char>, 1ul, 1, long int>, 1>]'
tensorflow/cc/ops/const_op.cc:88:1:   required from here
./tensorflow/core/public/tensor.h:411:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
```
"
127,cannot use bazel to compile tensorflow example codes,"tensorflow was successfully installed on my OSX10.11 system.
using ""import tensorflow"" in python donot report any error, and ""hello world"" application can be carried out.
but when i want to run the examples(http://tensorflow.org/tutorials/recurrent/index.md) in the tensorflow root directory, 
i typed ""bazel build -c opt tensorflow/models/rnn/ptb:ptb_word_lm""
it showed that:
ERROR: /Users/aaa/Develop/tools/tensorflow/tensorflow/python/BUILD:1: Extension file not found: 'google/protobuf/protobuf.bzl'.
ERROR: error loading package 'tensorflow/python': Extension file not found: 'google/protobuf/protobuf.bzl'.
INFO: Elapsed time: 0.057s

i don't know what is wrong.
any comment is appreciated.
"
126,"cpu version Installed successfully, but cannot import tensorflow in python.","My env is like this:

```
Red Hat Enterprise Linux Server release 5.5 (Tikanga)

python 2.7.3
```

I successfully installed tensorflow, using `pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl`

then I goes into `python`, then `import tensorflow as trf`, I got this error:

```

$ python
Python 2.7.3 (default, Nov  1 2013, 09:47:57) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-48)] on linux2
Type ""help"", ""copyright"", ""credits"" or ""license"" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File ""<stdin>"", line 1, in <module>
  File ""/users/jackson/pyenvs/tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py"", line 4, in <module>
    from tensorflow.python import *
  File ""/users/jackson/pyenvs/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py"", line 22, in <module>
    from tensorflow.python.client.client_lib import *
  File ""/users/jackson/pyenvs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/client_lib.py"", line 35, in <module>
    from tensorflow.python.client.session import InteractiveSession
  File ""/users/jackson/pyenvs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py"", line 11, in <module>
    from tensorflow.python import pywrap_tensorflow as tf_session
  File ""/users/jackson/pyenvs/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py"", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File ""/users/jackson/pyenvs/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py"", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /users/jackson/pyenvs/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: ELF file OS ABI invalid


```

Can I get some help on this pls?
"
125,Can anyone install it with cuda7.5 and cudnn 7.0?,"I installed it from source code. Everything is OK. 
  But when I  run '""""""bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu"""""" . 
  The errors are   1)Unable to load cuBLAS DSO,2)Unable to load cuDNN DSO,3)Unable to load cuFFT DSO,4)Unable to load cuRAND DSO.
"
124,tools/jdk: BUILD file not found on package path.,"While installing from source, I got this error

`ERROR: Loading of target '//tools/jdk:SingleJar_deploy.jar' failed; build aborted: no such package 'tools/jdk': BUILD file not found on package path.`
`ERROR: Loading failed; build aborted`

I already installed java8 as per bazel's instruction page. 
"
123,"Cant install, Mac - El Capitan - not a supported wheel","I try using this command in terminal 
$ pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
but i get ""tensorflow-0.5.0-py2-none-any.whl is not a supported wheel on this platform.""

I dont know what I did wrong, i am pretty sure pip is up to date, and I just downloaded homebrew for this...

I am using python with the anaconda package if that effects anything?

I have no idea what I am doing here, help please.
"
122,Windows Installation?,"Is it possible to install TF in windows environment?
I checked ""pip install"" is not supported in windows. 

Any plan for it?
"
121,ImportError: undefined symbol: clock_gettime,"I ran these successfully:

```
$ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
$ pip install --user /tmp/tensorflow_pkg/tensorflow-0.5.0-py2-none-any.whl
```

But the `convolutional.py` Python script gives an error:

```
$ python2.7 tensorflow/models/image/mnist/convolutional.py
Traceback (most recent call last):
  File ""tensorflow/models/image/mnist/convolutional.py"", line 13, in <module>
    import tensorflow.python.platform
  File ""/home/name/.local/lib/python2.7/site-packages/tensorflow/__init__.py"", line 4, in <module>
    from tensorflow.python import *
  File ""/home/name/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py"", line 22, in <module>
    from tensorflow.python.client.client_lib import *
  File ""/home/name/.local/lib/python2.7/site-packages/tensorflow/python/client/client_lib.py"", line 35, in <module>
    from tensorflow.python.client.session import InteractiveSession
  File ""/home/name/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py"", line 11, in <module>
    from tensorflow.python import pywrap_tensorflow as tf_session
  File ""/home/name/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py"", line 26, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File ""/home/name/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py"", line 22, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /home/name/.local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: 
undefined symbol: clock_gettime
```
"
120,TensorFlow session.run() overhead for graphs with few flops,"The following code will take 10 seconds to run:

``` python
with tf.Session():
    for _ in range(1000):
        tf.constant(0).eval()
```

Now, this might not be an issue for large-scale machine learning, but it makes running the graph in real-time very hard. I was trying to port a forward simulation model from Theano to TensorFlow, where 1000 runs of forward simulation took 0.2s in Theano vs. 17s in TensorFlow, and over half of the time was taken by this `session.run()` overhead.
"
119,Bazel can't build protobuf,"The errors of  `bazel build -c opt //tensorflow/tools/pip_package:build_pip_package` are always some header files of protobuf are not found. Related to 
https://github.com/google/protobuf/issues/925. I was wondering why nobody reported this yesterday.

```
INFO: Found 1 target...
INFO: From Compiling google/protobuf/src/google/protobuf/compiler/code_generator.cc [for host]:
google/protobuf/src/google/protobuf/compiler/code_generator.cc:39:43: fatal error: google/protobuf/stubs/strutil.h: No such file or directory
 #include <google/protobuf/stubs/strutil.h>
                                           ^
compilation terminated.
ERROR: /home/user/Codes/DeepLearning/tensorflow/google/protobuf/BUILD:166:1: C++ compilation of rule '//google/protobuf:protoc_lib' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections ... (remaining 32 argument(s) skipped).
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.205s, Critical Path: 0.88s
```
"
118,"""help wanted"" I cannot get the TensorBoard working, I am following the given tutorial","*_I am having trouble writing the log file to be able to visualize it in TensorBoard. Can somebody point me in the right direction? I have followed the code given in the tutorial. When run I get the error: *_ 
-  ""expected %s got %s."" % (cls.**name**, type(msg).**name**))
  TypeError: Parameter to MergeFrom() must be instance of same class: expected GraphDef got Graph. for field Event.graph_def*

The error is said to be on line:

``` python
summary_writer = tf.train.SummaryWriter('/Users/Cristian/Desktop/log', sess.graph)
```

**My code:**

``` Python
import input_data
import tensorflow as tf


print ""Start program""
mnist = input_data.read_data_sets(""MNIST_data/"", one_hot=True)
print ""Done loading images""

x = tf.placeholder(""float"", [None, 784])
W = tf.Variable(tf.zeros([784,10]))
b = tf.Variable(tf.zeros([10]))

y = tf.nn.softmax(tf.matmul(x,W) + b)

y_ = tf.placeholder(""float"", [None,10])

print ""Done init""

cross_entropy = -tf.reduce_sum(y_*tf.log(y))
train_step = tf.train.GradientDescentOptimizer(0.01).minimize(cross_entropy)


print ""Done loading vars""

init = tf.initialize_all_variables()
print ""Done init vars""

sess = tf.Session()
sess.run(init)

print '------'
print type(sess.graph_def)


correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, ""float""))

acc = tf.scalar_summary(""Accuracy:"", accuracy)

merged_summary_op = tf.merge_all_summaries()
summary_writer = tf.train.SummaryWriter('/Users/Cristian/Desktop/log', sess.graph)

print ""Session started""


for i in range(2000):
  batch_xs, batch_ys = mnist.train.next_batch(100)
  sess.run(train_step, feed_dict={x: batch_xs, y_: batch_ys})
  if i % 100 == 0:
    print sess.run(accuracy, feed_dict={x: mnist.test.images, y_: mnist.test.labels})
    summary_str = sess.run(merged_summary_op)
    summary_writer.add_summary(summary_str, i)


print ""Done training""

correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))

accuracy = tf.reduce_mean(tf.cast(correct_prediction, ""float""))


print sess.run(accuracy, feed_dict={x: mnist.test.images, y_: mnist.test.labels})

```
"
117,"TensorBoard logdir path, if relative, is relative to $HOME","It took me a while to figure this out and I'm not entirely sure that my interpretation is correct, but even if I'm not in $HOME, running tensorboard --logdir=. will give a list of directories in my home, and passing an absolute path appears to pick things up correctly. It is somewhat counterintuitive to me that relative paths are not relative to the current directory, so maybe that's something to document, disallow, or change?

Thanks, this library is amazing!
"
116,When will you have a version of TensorFlow for Win10/8/7?,"When will that happen?  Should I do it myself?
"
115,Incorrect matrix math in tutorial at:  http://www.tensorflow.org/tutorials/mnist/beginners/index.md,"On the [generally wonderful beginner's documentation](http://www.tensorflow.org/tutorials/mnist/beginners/index.md), there is the following incorrect matrix math ![matrix math](http://api.tensorflow.org/system/image/body/1707/softmax-regression-scalarequation.png)

---

The x's are incorrect.  Each element should include x{sub}1, x{sub}2, and x{sub}3.  This will be obvious upon looking at the correct vector representation on that same page immediately underneath.  Overall the documentation seems awesome so far!  :smiley: 
"
114,Matrix multiplication in softmax documentation carried out incorrectly,"In the softmax documentation on page:

http://tensorflow.org/tutorials/mnist/beginners/index.md

There is a set of images showing an example of what the function is doing:

![image](https://cloud.githubusercontent.com/assets/5950006/11081692/e3c5dc3c-87ec-11e5-8e9a-6ed0b0ace7c6.png)

Then the ""xs"" are pulled out so that we have the vectors Wx. But the coefficients in the image above is incorrect. If the image below, also take form the docs, shows the true form then the equations in the above image should be:

y1 = W1,1**x1** + W1,2**x2** + W1,3**x3** + b1

instead of:

y1 = W1,1**x1** + W1,2**x1** + W1,3**x1** + b1

![image](https://cloud.githubusercontent.com/assets/5950006/11081715/38e3fdb6-87ed-11e5-8621-ac80926f2c03.png)
"
112,EC2 g2.2xlarge: Ignoring gpu device (GRID K520) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.,"I got this error while running on an Amazon EC2 g2.2xlarge instance:

```
tensorflow/core/common_runtime/gpu/gpu_device.cc:611
 Ignoring gpu device (device: 0, name: GRID K520, pci bus id: 0000:00:03.0) 
with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
Invalid argument: Cannot assign a device to node 'Const/_2': Could not satisfy explicit device specification '/gpu:0'
 [[Node: Const/_2 = Const[dtype=DT_INT32, value=Tensor<type: int32 shape: [] values: 0>, _device=""/gpu:0""]()]])
```
"
111,configure script hardcodes location of cuda that makes it fail on OSX,"Cuda installation on OSX is at $CUDA_TOOLKIT_PATH/lib (not lib64), and on OSX the shared libraries are end in .dylib (not .so).

```
  if [ -e ""$CUDA_TOOLKIT_PATH/lib64/libcudart.so.7.0"" ]; then
    break
  fi
  echo ""Invalid path to CUDA 7.0 toolkit. ${CUDA_TOOLKIT_PATH}/lib64/libcudart.so.7.0 cannot be found""
```
"
110,"Support for Redhat, Centos and many superclusters","Many clusters system using module with Redhat or Centos < 7 which is **glibc 2.12**

Since, **bazel** requires **glibc 2.14** and the prebuilt version for linux requires **glibc 2.17**. It is hopeless to make tensorflow run on clusters.

Referred to this issue reported on bazel: https://github.com/bazelbuild/bazel/issues/583
"
109, C++ compilation of rule '//tensorflow/python:tf_session_helper' failed,"I am trying to compile build_pip_package on Ubuntu 12.04 with gcc 4.8, but it gives an error during compilation:

```
$ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package --verbose_failures

tensorflow/python/client/tf_session_helper.cc:418:41: error: 'PyArray_SHAPE' was not declared in this scope
   dims.push_back(PyArray_SHAPE(array)[i]);

ERROR: /home/local/ANT/x/tensorflow/tensorflow/python/BUILD:666:1: C++ compilation of rule '//tensorflow/python:tf_session_helper' failed: gcc failed: error executing command 
  (cd /home/local/ANT/x/.cache/bazel/_bazel_x/29843df2d2b24eaae7acd7ee881b7bec/tensorflow && \
  exec env - \
    INTERCEPT_LOCALLY_EXECUTABLE=1 \
    PATH=/home/local/ANT/x/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/games:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin \
  /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -iquote . -iquote bazel-out/local_linux-opt/genfiles -isystem google/protobuf/src -isystem bazel-out/local_linux-opt/genfiles/google/protobuf/src -isystem tools/cpp/gcc3 -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/local_linux-opt/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/local_linux-opt/genfiles/external/png_archive/libpng-1.2.53 -isystem external/re2 -isystem bazel-out/local_linux-opt/genfiles/external/re2 -isystem third_party/gpus/cuda -isystem bazel-out/local_linux-opt/genfiles/third_party/gpus/cuda -isystem third_party/gpus/cuda/include -isystem bazel-out/local_linux-opt/genfiles/third_party/gpus/cuda/include -isystem third_party/eigen3 -isystem bazel-out/local_linux-opt/genfiles/third_party/eigen3 -I/usr/include/python2.7 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__=""redacted""' '-D__TIMESTAMP__=""redacted""' '-D__TIME__=""redacted""' '-frandom-seed=bazel-out/local_linux-opt/bin/tensorflow/python/_objs/tf_session_helper/tensorflow/python/client/tf_session_helper.pic.o' -MD -MF bazel-out/local_linux-opt/bin/tensorflow/python/_objs/tf_session_helper/tensorflow/python/client/tf_session_helper.pic.d -fPIC -c tensorflow/python/client/tf_session_helper.cc -o bazel-out/local_linux-opt/bin/tensorflow/python/_objs/tf_session_helper/tensorflow/python/client/tf_session_helper.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: gcc failed: error executing command 
  (cd /home/local/ANT/x/.cache/bazel/_bazel_x/29843df2d2b24eaae7acd7ee881b7bec/tensorflow && \
  exec env - \
    INTERCEPT_LOCALLY_EXECUTABLE=1 \
    PATH=/home/local/ANT/x/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/games:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin \
  /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -iquote . -iquote bazel-out/local_linux-opt/genfiles -isystem google/protobuf/src -isystem bazel-out/local_linux-opt/genfiles/google/protobuf/src -isystem tools/cpp/gcc3 -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/local_linux-opt/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/local_linux-opt/genfiles/external/png_archive/libpng-1.2.53 -isystem external/re2 -isystem bazel-out/local_linux-opt/genfiles/external/re2 -isystem third_party/gpus/cuda -isystem bazel-out/local_linux-opt/genfiles/third_party/gpus/cuda -isystem third_party/gpus/cuda/include -isystem bazel-out/local_linux-opt/genfiles/third_party/gpus/cuda/include -isystem third_party/eigen3 -isystem bazel-out/local_linux-opt/genfiles/third_party/eigen3 -I/usr/include/python2.7 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__=""redacted""' '-D__TIMESTAMP__=""redacted""' '-D__TIME__=""redacted""' '-frandom-seed=bazel-out/local_linux-opt/bin/tensorflow/python/_objs/tf_session_helper/tensorflow/python/client/tf_session_helper.pic.o' -MD -MF bazel-out/local_linux-opt/bin/tensorflow/python/_objs/tf_session_helper/tensorflow/python/client/tf_session_helper.pic.d -fPIC -c tensorflow/python/client/tf_session_helper.cc -o bazel-out/local_linux-opt/bin/tensorflow/python/_objs/tf_session_helper/tensorflow/python/client/tf_session_helper.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 3.223s, Critical Path: 2.46s
```
"
108,Building a shared libary,"Is there a way to ask the build system to build a shared library that one can link a program written using the C++ API against? My apologies for this simple question, but I am very unfamiliar with this build system.
"
107,Truncated backprop docs are confusing,"The docs (http://tensorflow.org/tutorials/recurrent/index.md) imply that to truncate backprop, you feed blocks of fixed (time) length (`num_steps`) to `RNNCell`.  

Does this mean that if I have sentences of length 100 and I want to truncate by 20 time steps, I would send tensors of shape `batch_size x 20`?

If I'm right and you are supposed to feed blocks of fixed length inputs in an inner loop, don't I need to initialize the initial state from the previous block for the forward pass to be right.  But if I do use the final hidden state of the previous block as the next initial state, won't the autograd backpropagate all the way through.  In other words, looping over blocks of intervals and then within each in block while connecting the previous block's hidden state to the next block's initial state seems equivalent to just looping over time in the first place.

Am I missing something?
"
106,Ubuntu installation error using pip,"Hi,

I am using Ubuntu 12.04 amd64 with Python 2.7.3. I have used the following command to want to install tensorflow :

pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl

I get the following error :
### 

/usr/bin/pip run on Wed Nov 11 07:00:36 2015
Downloading/unpacking https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
  Downloading from URL https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
  Running setup.py egg_info for package from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
    Traceback (most recent call last):
      File ""<string>"", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-k5gImY-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File ""<string>"", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip-k5gImY-build/setup.py'

Command python setup.py egg_info failed with error code 1
Exception information:
Traceback (most recent call last):
  File ""/usr/lib/python2.7/dist-packages/pip/basecommand.py"", line 126, in main
    self.run(options, args)
  File ""/usr/lib/python2.7/dist-packages/pip/commands/install.py"", line 223, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File ""/usr/lib/python2.7/dist-packages/pip/req.py"", line 980, in prepare_files
    req_to_install.run_egg_info()
  File ""/usr/lib/python2.7/dist-packages/pip/req.py"", line 216, in run_egg_info
    command_desc='python setup.py egg_info')
  File ""/usr/lib/python2.7/dist-packages/pip/**init**.py"", line 255, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command python setup.py egg_info failed with error code 1
### 

The output of ""sudo pip --version"" is ""pip 1.0 from /usr/lib/python2.7/dist-packages (python 2.7)"".

I want to know that is my pip version too low. What else should I try ? Any idea ?

Thanks for any suggestion.

Lawrence
"
105,Can't build from source?,"I followed the instructions [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md) but failed at this step.

```
➜  tensorflow git:(master) bazel build -c opt //tensorflow/cc:tutorials_example_trainer
..........
INFO: Elapsed time: 2.016s
java.lang.NoClassDefFoundError: com/jcraft/jsch/JSchException
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:109)
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
        at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
        at com.google.devtools.build.lib.bazel.repository.GitCloneFunction.compute(GitCloneFunction.java:124)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:725)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$2.run(AbstractQueueVisitor.java:436)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.jcraft.jsch.JSchException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 16 more
```

My environment is Ubuntu 14.04 LTS without  GPU.
"
104,Support for python 3,"It would be nice to have support for python 3 
"
103,Alpine Linux: __isnanf: symbol not found ,"I build tensorflow in alpine Linux in docker successfully, but when run the test, I got below error. Anything I missed?

```
$ python
>>> import tensorflow as tf
...
  File ""/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py"", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: Error relocating /usr/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: __isnanf: symbol not found
>>> exit()

/ # nm /usr/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so |grep isnanf
                 U __isnanf@@GLIBC_2.2.5
/ #
```

How to fix the issue `__isnanf: symbol not found`

`Dockerfile` for your reference: https://github.com/BWITS/Docker-builder/blob/master/tensorflow/alpine/Dockerfile
"
101,Neural Translation Model example fails due to missing EN tokens ,"The S2S Neural Translation example (tensorflow/models/rnn/translate)  runs into this error:

> tensorflow.python.platform.default._gfile.FileError: [Errno 2] No such file or directory: 'data/giga-fren.release2.ids40000.en'

The issue seems to be in prepare_wmt_data of data_utils.py. Here, instead of creating a new file for the EN tokens, the FR tokens are overwritten by EN tokens:

> data_to_token_ids(train_path + "".en"", fr_train_ids_path, fr_vocab_path)

The fix seems to be as simple as changing that line to:

> data_to_token_ids(train_path + "".en"", en_train_ids_path, en_vocab_path)
"
100,Installing from source - problem with bazel,"I was following the instructions for installing from source. However, installing bazel from the specified checkout, however I encountered the error from this issue:
https://github.com/bazelbuild/bazel/issues/321
This was fixed by editing the compile.sh and changing the `c++0x` to `c++11`. However now I'm getting the following issue, which unfortunately did not find any relevant information from google:

```
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh build /path/to/bazel
🍃  Building Bazel from scratch............
🍃  Building Bazel with Bazel.
.Extracting Bazel installation...
Sending SIGTERM to previous Bazel server (pid=23336)... done.
.................
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
INFO: From Compiling src/main/cpp/blaze_util_posix.cc:
gcc: unrecognized option '-no-canonical-prefixes'
src/main/cpp/blaze_util_posix.cc: In function 'void blaze::ExecuteProgram(const std::string&, const std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)':
src/main/cpp/blaze_util_posix.cc:35: error: expected initializer before ':' token
src/main/cpp/blaze_util_posix.cc:40: warning: the address of 'cwd' will always evaluate as 'true'
src/main/cpp/blaze_util_posix.cc:41: error: expected primary-expression before 'if'
src/main/cpp/blaze_util_posix.cc:41: error: expected ')' before 'if'
src/main/cpp/blaze_util_posix.cc:45: error: 'cwd' was not declared in this scope
At global scope:
cc1plus: warning: unrecognized command line option ""-Wno-free-nonheap-object""
ERROR: /home/ucl/eisuc212/python_modules/bazel/src/main/cpp/BUILD:22:1: C++ compilation of rule '//src/main/cpp:client' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -DBLAZE_OPENSOURCE -iquote . ... (remaining 20 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //src:bazel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 11.004s, Critical Path: 1.36s
```

Do you know for any workarounds or at least idea how to fix it. 
"
98,MAC pip install operation not permitted,"MBP 2014. Intel CPU.

Any thoughts? Below was running with sudo

Exception:
Traceback (most recent call last):
  File ""/Library/Python/2.7/site-packages/pip/basecommand.py"", line 211, in main
    status = self.run(options, args)
  File ""/Library/Python/2.7/site-packages/pip/commands/install.py"", line 311, in run
    root=options.root_path,
  File ""/Library/Python/2.7/site-packages/pip/req/req_set.py"", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File ""/Library/Python/2.7/site-packages/pip/req/req_install.py"", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File ""/Library/Python/2.7/site-packages/pip/req/req_uninstall.py"", line 125, in remove
    renames(path, new_path)
  File ""/Library/Python/2.7/site-packages/pip/utils/**init**.py"", line 315, in renames
    shutil.move(old, new)
  File ""/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py"", line 302, in move
    copy2(src, real_dst)
  File ""/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py"", line 131, in copy2
    copystat(src, dst)
  File ""/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py"", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-bX2I_b-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
"
97,How to extract predictions,"Hi, can someone either point to code example or documentation how to extract final predictions after the training the model. For example, it would be nice to complement existing tutorials, e.g. mnist, and show additional (final) step to get prediction out of the trained model.
"
96,tensorflow-0.5.0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.,"Hello,I got the error when i  execute:""pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl""--------[ tensorflow-0.5.0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.].
"
95,Greedy heuristics may not find the optimal node placement,"The nodes have computational costs and the edges have communication costs making the placement problem very similar to finding the [minimum cost flow](https://en.wikipedia.org/wiki/Minimum-cost_flow_problem) of the computation graph. There are very [simple implementations](https://github.com/search?o=desc&q=Min+cost+flow&ref=searchresults&s=forks&type=Repositories&utf8=%E2%9C%93) to get the global optimal solution(s).
"
94,Abandon gerrit and use github for everything,"Gerrit review workflow is very hard to maintain and follow. A lot of project abandoned it and turns to github finally.

Really hope tensorflow will use github for all the cooperation workflow. Google [Kubernetes](https://github.com/kubernetes/kubernetes) and [Docker](https://github.com/docker/docker) are all excellent examples  for how to use github maintain a huge and global scale open source project successfully.

github + travis CI + slack is awesome.  Just make everything be a PR :)
"
93," build failed!  File ""/usr/lib/python2.7/encodings/__init__.py"", line 123       raise CodecRegistryError,\","ubgpu@ubgpu:~/github/tensorflow$ PYTHONPATH=/usr/lib/python2.7 bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
Fatal Python error: Py_Initialize: Unable to get the locale encoding
  File ""/usr/lib/python2.7/encodings/**init**.py"", line 123
    raise CodecRegistryError,\
                            ^
SyntaxError: invalid syntax
Aborted (core dumped)
ubgpu@ubgpu:~/github/tensorflow$ 
"
92,do we have plans for java api?,"I can see there is only python and C++ api, do we have any plans for java api? or workarounds?
"
91,import six.moves.copyreg as copyreg error,"ENV: Mac OS X 10.10, System shipped Python 2.7, six 10.10.0
In this file, I need to replace `import six.moves.copyreg as copyreg` with `from six.moves import copyreg`
/Library/Python/2.7/site-packages/google/protobuf/internal/python_message.py
"
89,Typo in `/tutorials/mnist/beginners/index.md`,"```
First, `tf.log` computes the logarithm of each element of `y`. Next, we multiply each element of `y_` with the corresponding element of `tf.log(y_)`
```

should be

```
First, `tf.log` computes the logarithm of each element of `y`. Next, we multiply each element of `y_` with the corresponding element of `tf.log(y)`
```
"
88,Unable to run tensorboard,"Hi all,
I'm trying to use tensorboard but I can't find the tensorboard executable in my path. I installed tensorflow with pip.
When trying to run it from source I got the following error 

```
WARNING:root:IOError [Errno 2] No such file or directory: '/../tensorflow/external/paper-toggle-button/paper-toggle-button.html' on path /.../tensorflow/external/paper-toggle-button/paper-toggle-button.html
```
"
86,GPU implementations for more ops,"1. Loads of operations in the embedding example are not supported on GPU. Some documentation   detailing this would be good.
2. I tried to get around the problem by using 'tf.ConfigProto(allow_soft_placement=True)'. However now I get 'Executor failed to create kernel. Invalid argument: AttrValue must not have reference type value of float_ref for attr 'tensor_type'

Thanks
Abhishek
"
85,C++ API neural net examples,"From looking at the code, it seems most NN operations are of course available at C++ level (I couldn't find dropout, but I guess it is formalized as one of the randomized operations).

The C++ documentation outside the code itself is rather scarce however, which I fully understand for a first release, with priority given to Python.

I wouldn't be surprised that some Googlers are actually working from the straight C++ API. Is there any plan to provide some more straightforward toy applications in C++ ? If not, please just ignore and close this issue. 

Otherwise, I am interested in any pointers and I can help rewriting stuff such as seq2seq and rnn from the C++ point of view. One of the useful cornerpoints to look at could be the intersection of the Python API with the underlying C++ engine, but I haven't been able to locate it clearly yet.
"
84,Septation of Generalised DAG / Data Flow Programming Framework and ML Components,"Can you make a clear separation between DAG / Data Flow Programming Framework and the ML framework. The former can have more applications than ML and will open more avenues for its use.
"
83,can't install on ubuntu 12.04,"when i install it use the command
sudo pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl

there is error 
No such file or directory: '/tmp/pip-byRUCn-build/setup.py'
"
82,bazel compile error,"with gcc (GCC) 4.8.2.
git clone ;
cd bazel ;
./compile.sh; 
Is there any requirement of gcc version?
I get this:

<pre>WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
INFO: From Compiling src/main/tools/build-runfiles.cc:
gcc: unrecognized option '-no-canonical-prefixes'
src/main/tools/build-runfiles.cc: In member function 'void RunfilesCreator::EnsureDirReadAndWritePerms(const std::string&)':
src/main/tools/build-runfiles.cc:342: warning: comparison between signed and unsigned integer expressions
At global scope:
cc1plus: warning: unrecognized command line option ""-Wno-free-nonheap-object""
INFO: From Compiling src/main/cpp/util/port.cc:
gcc: unrecognized option '-no-canonical-prefixes'
INFO: From Compiling src/main/cpp/util/errors.cc:
gcc: unrecognized option '-no-canonical-prefixes'
INFO: From Compiling src/main/native/process.cc:
gcc: unrecognized option '-no-canonical-prefixes'
INFO: From Linking src/main/tools/build-runfiles:
gcc: unrecognized option '-no-canonical-prefixes'
INFO: From Compiling src/main/cpp/util/strings.cc:
gcc: unrecognized option '-no-canonical-prefixes'
src/main/cpp/util/strings.cc: In function 'void blaze_util::JoinStrings(const std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, char, std::string*)':
src/main/cpp/util/strings.cc:90: error: expected initializer before ':' token
src/main/cpp/util/strings.cc:305: error: expected primary-expression at end of input
src/main/cpp/util/strings.cc:305: error: expected ';' at end of input
src/main/cpp/util/strings.cc:305: error: expected primary-expression at end of input
src/main/cpp/util/strings.cc:305: error: expected ')' at end of input
src/main/cpp/util/strings.cc:305: error: expected statement at end of input
src/main/cpp/util/strings.cc:89: warning: unused variable 'first'
src/main/cpp/util/strings.cc:305: error: expected '}' at end of input
src/main/cpp/util/strings.cc: At global scope:
src/main/cpp/util/strings.cc:305: error: expected '}' at end of input
cc1plus: warning: unrecognized command line option ""-Wno-free-nonheap-object""
ERROR: /data/qianmin/project/bazel/src/main/cpp/util/BUILD:31:1: C++ compilation of rule '//src/main/cpp/util:strings' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -DBLAZE_OPENSOURCE -iquote . ... (remaining 18 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //src:bazel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 7.541s, Critical Path: 1.41s</pre>
"
81,Installed from source; unable to import tensorflow,"ariw@clairvoyance:~/tensorflow$ python
Python 2.7.6 (default, Jun 22 2015, 18:00:18) 
[GCC 4.8.2] on linux2
Type ""help"", ""copyright"", ""credits"" or ""license"" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File ""<stdin>"", line 1, in <module>
  File ""tensorflow/**init**.py"", line 4, in <module>
    from tensorflow.python import *
  File ""tensorflow/python/**init**.py"", line 13, in <module>
    from tensorflow.core.framework.graph_pb2 import *
ImportError: No module named core.framework.graph_pb2
>>> exit()
"
80,tensorboard gulp - analytics.js missing,"installing frontend dependencies works fine from a clean ubuntu install:
npm install
bower install
tsd install

compiling all deps with gulp vulcanize throws an error however:

```
[~/tensorflow/tensorflow/tensorboard]$ gulp vulcanize                                                                                                                             
[07:29:48] Using gulpfile ~/tensorflow/tensorflow/tensorboard/gulpfile.js
[07:29:48] Starting 'compile.all'...
[07:29:48] Starting 'tslint-strict'...
[07:29:51] Finished 'tslint-strict' after 3.24 s
[07:29:53] Finished 'compile.all' after 5.34 s
[07:29:53] Starting 'vulcanize'...
[07:29:53] Finished 'vulcanize' after 6.08 ms
ERROR finding /home/ubuntu/tensorflow/tensorflow/tensorboard/lib/js/analytics.js
```

not a huge problem as the frontend works just fine with _gulp server_
"
79,segmentation fault when running convolutional.py,"I am running tensorflow/models/image/mnist/convolutional.py. I get:

ariw@clairvoyance:~/tensorflow$ python tensorflow/models/image/mnist/convolutional.py 
Succesfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Succesfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Succesfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Succesfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 2
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 2
Initialized!
zsh: segmentation fault (core dumped)  python tensorflow/models/image/mnist/convolutional.py

Thoughts?
"
78,Scalar Equation is incorrect ? Documentation,"```
http://tensorflow.org/tutorials/mnist/beginners/index.md#the_mnist_data

https://upload.wikimedia.org/math/7/3/f/73fc7ef1bf6f6822115c41cff58535e1.png

http://api.tensorflow.org/system/image/body/1704/softmax-regression-scalargraph.png

http://api.tensorflow.org/system/image/body/1707/softmax-regression-scalarequation.png

http://api.tensorflow.org/system/image/body/1705/softmax-regression-vectorequation.png

scalar equation should be:
[W11 * X1 + W12 * X2 +  W13 * X3 + b1]
[W21 * X1 +W22 * X2 + W23 * X3 + b2]
[W31 * X1 + W32 * X2 + W33 * X3 + b3] 
```
"
77,1st Class Windows Support,"Provide the same level of documentation and resources on using and running on windows. Also test if it works on Windows.
"
76,cuDNN v2 (6.5) not available anymore,"I don't see how I can run TensorFlow with cuDNN: cuDNN v2 (6.5) doesn't seem to be available for download from nVidia anymore, but it's the only version actually supported by TensorFlow.
"
75,No module named copy_reg - Installation Issue,"Currently this is my output after installing Tensorflow. I thought it installed six as well, but was wondering why copyreg doesn't exist in six. Anyone know what to do?

tensorflow % python                                                   

Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type ""help"", ""copyright"", ""credits"" or ""license"" for more information.

Input:
import tensorflow as tf

Result:
Traceback (most recent call last):
  File ""<stdin>"", line 1, in <module>
  File ""/Library/Python/2.7/site-packages/tensorflow/**init**.py"", line 4, in <module>
    from tensorflow.python import *
  File ""/Library/Python/2.7/site-packages/tensorflow/python/**init**.py"", line 13, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File ""/Library/Python/2.7/site-packages/tensorflow/core/framework/graph_pb2.py"", line 8, in <module>
    from google.protobuf import reflection as _reflection
  File ""/Library/Python/2.7/site-packages/google/protobuf/reflection.py"", line 58, in <module>
    from google.protobuf.internal import python_message as message_impl
  File ""/Library/Python/2.7/site-packages/google/protobuf/internal/python_message.py"", line 59, in <module>
    import six.moves.copyreg as copyreg
ImportError: No module named copyreg
"
74,Cannot run the android example on Android 5.1.1,"The android example APK can be successfully compiled and installed (except that adb -g option is not recognized), however, at launch it shows ""Failed"" without showing any camera view.

Device is a Nexus 6 with Android 5.1.1.

This is what I have in WORKSPACE

```
# Uncomment and update the paths in these entries to build the Android demo.
android_sdk_repository(
    name = ""androidsdk"",
    api_level = 22, 
    build_tools_version = ""22.0.1"",
    # Replace with path to Android SDK on your system
    path = ""/home/victor/Android/Sdk/"",
)
#
android_ndk_repository(
    name=""androidndk"",
    path=""/home/victor/Downloads/android-ndk-r10e"",
    api_level=21)
```

logcat information

```
I/tensorflow( 7634): CameraConnectionFragment: Opening camera preview: 4160x3120
E/CameraDeviceClient( 1539): beginConfigure: Not implemented yet.
W/CameraDeviceClient( 1539): createStream: Camera 0: Forcing asynchronous mode for stream
W/CameraDeviceClient( 1539): createStream: Camera 0: Overriding format 0x1 to IMPLEMENTATION_DEFINED
E/QCamera3HWI( 1539): int qcamera::QCamera3HardwareInterface::configureStreams(camera3_stream_configuration_t*): Number of streams on ISP encoder path exceeds limits of 2
W/CameraDevice-JV-0( 7634): Stream configuration failed
E/CameraCaptureSession( 7634): Session 0: Failed to create capture session; configuration failed
I/tensorflow( 7634): CameraConnectionFragment: Getting assets.
I/native  ( 7634): tensorflow/examples/android/jni/tensorflow_jni.cc:41 Compute graph already loaded. skipping.
I/tensorflow( 7634): CameraConnectionFragment: Tensorflow initialized.
```
"
73,No plan for official doc of any other languages than English?,"I am planning on translating the docs into Korean, should I be distributing it on my own?
"
72,Target //tensorflow/tools/pip_package:build_pip_package failed to build on OSX,"```
ERROR: /Users/delip/Softwares/tensorflow/tensorflow/tensorflow.bzl:224:3: C++ compilation of rule '//tensorflow/python:tf_session_helper' failed: osx_gcc_wrapper.sh failed: error executing command tools/cpp/osx_gcc_wrapper.sh '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections ... (remaining 52 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

I recently checked out the repo

```
$ git log | head -5
commit 41930f0b81b52a34fb56d921c9bad65c36168323
Author: Vijay Vasudevan <vrv@google.com>
Date:   Mon Nov 9 18:42:53 2015 -0800

    TensorFlow: Upstream a batch of changes to git.
```
"
71,Can't install from source if I don't have a GPU? ,"My os X: EI Captian version 10.11.1 
I tried install from the source. However, running ""$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg"" this make me error.  I got following error message. I think I don't have a GPU in my mac. Is there anyway that I can isnstall from source even though I don't have a GPU ? 

sangpil_kim@ ~/git/tensorflow $ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
.......
INFO: Found 1 target...
INFO: From Executing genrule //third_party/gpus/cuda:cuda_config_check:
/bin/bash: touch: command not found
ERROR: /Users/sangpil_kim/git/tensorflow/third_party/gpus/cuda/BUILD:143:1: Executing genrule //third_party/gpus/cuda:cuda_config_check failed: bash failed: error executing command /bin/bash -c 'source tools/genrule/genrule-setup.sh; touch bazel-out/local_darwin-opt/genfiles/third_party/gpus/cuda/cuda.config': com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 127.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 79.345s, Critical Path: 0.32s
-bash: tail: command not found
-bash: sed: command not found
"
70,Human Consumable Language Independent DSL,"Is there a possibility to have a human consumable language independent DSL from which a program in any desired language can be generated.
"
69,models/rnn/ptb not included in pip package,
68,Typo,"http://tensorflow.org/tutorials/mnist/beginners/index.md

...with the corresponding element of tf.log(y_)
...with the corresponding element of tf.log(y)

Is this the right place to report typo?
"
67,no such package '@jpeg_archive//': Error downloading from ijg.org,"I'm getting the following error when trying to build from source:

```
$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
ERROR: /home/name/tmp/tensorflow/tensorflow/core/platform/default/build_config/BUILD:36:1: no such package '@jpeg_archive//': Error downloading from http://www.ijg.org/files/jpegsrc.v9a.tar.gz to /home/name/.cache/bazel/_bazel_mddreyer/44409223966f9cb8e480014c7f376bcc/external/jpeg_archive: Error downloading http://www.ijg.org/files/jpegsrc.v9a.tar.gz to /home/name/.cache/bazel/_bazel_mddreyer/44409223966f9cb8e480014c7f376bcc/external/jpeg_archive/jpegsrc.v9a.tar.gz: Server returned HTTP response code: 403 for URL: http://www.ijg.org/files/jpegsrc.v9a.tar.gz and referenced by '//tensorflow/core/platform/default/build_config:platformlib'.
ERROR: Loading failed; build aborted.
```
"
66,compilation error,"Just did a git clone to build from source as described in documentation and got this at compile time (without CUDA/GPG support) ...

INFO: From Compiling tensorflow/core/kernels/pad_op.cc:
In file included from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:94:0,
                 from ./tensorflow/core/framework/tensor_types.h:4,
                 from ./tensorflow/core/kernels/pad_op.h:6,
                 from tensorflow/core/kernels/pad_op.cc:5:
third_party/eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorBase.h: In instantiation of 'const Eigen::TensorPaddingOp<const PaddingDimensions, const Derived> Eigen::TensorBase<Derived, 0>::pad(const PaddingDimensions&) const [with PaddingDimensions = Eigen::array<std::pair<int, int>, 0ul>; Derived = Eigen::TensorMap<Eigen::Tensor<const std::complex<float>, 0ul, 1, long int>, 1>]':
./tensorflow/core/kernels/pad_op.h:20:22:   required from 'void tensorflow::functor::Pad<Device, T, Dims>::operator()(const Device&, typename tensorflow::TTypes<T, Dims>::Tensor, typename tensorflow::TTypes<T, Dims>::ConstTensor, Eigen::array<std::pair<int, int>, Dims>) [with Device = Eigen::ThreadPoolDevice; T = std::complex<float>; int Dims = 0; typename tensorflow::TTypes<T, Dims>::Tensor = Eigen::TensorMapEigen::Tensor<std::complex<float, 0ul, 1, long int>, 1>; typename tensorflow::TTypes<T, Dims>::ConstTensor = Eigen::TensorMap<Eigen::Tensor<const std::complex<float>, 0ul, 1, long int>, 1>]'
tensorflow/core/kernels/pad_op.cc:112:27:   required from 'void tensorflow::PadOp<Device, T>::Operate(tensorflow::OpKernelContext_, typename tensorflow::TTypes<T, Dims>::ConstTensor, tensorflow::TTypes<int>::ConstMatrix, tensorflow::Tensor_) [with int Dims = 0; Device = Eigen::ThreadPoolDevice; T = std::complex<float>; typename tensorflow::TTypes<T, Dims>::ConstTensor = Eigen::TensorMap<Eigen::Tensor<const std::complex<float>, 0ul, 1, long int>, 1>; tensorflow::TTypes<int>::ConstMatrix = Eigen::TensorMap<Eigen::Tensor<const int, 2ul, 1, long int>, 1>]'
tensorflow/core/kernels/pad_op.cc:73:16:   required from 'void tensorflow::PadOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = std::complex<float>]'
tensorflow/core/kernels/pad_op.cc:159:1:   required from here
third_party/eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorBase.h:703:5: note: the ABI of passing structure with complex float member has changed in GCC 4.4
     pad(const PaddingDimensions& padding) const {
     ^
Target //tensorflow/cc:tutorials_example_trainer up-to-date:
  bazel-bin/tensorflow/cc/tutorials_example_trainer
INFO: Elapsed time: 494.466s, Critical Path: 472.43s
shanker@blackhole ~/projects/tensorflow $ 
"
65,FR: Change TensorBoard image interpolation method,"Right now tensorboard uses bilinear interpolation, according to @poolio this is unusuable for small resolution photos and nearest neighbor is preferred
"
64,Mac: OSError: [Errno 1] Operation not permitted: '/tmp/pip-XcfgD6-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info',
63,Specify output tensor for ops from python,"Sometimes for efficiency it's good to specify the memory in which to write the output of an op (e.g writing to a contiguous part of memory from two functions to save a concat call). Is this supported (it's not in the docs)?
"
62,"CUDNN error on ""import tensorflow as tf"" for gpu version","I'm getting the following error when I try to run the gpu version.

I tensorflow/stream_executor/dso_loader.cc:77] LD_LIBRARY_PATH: :/usr/local/cuda-7.0/lib:/usr/local/cuda-7.0/lib64:/usr/local/cuda-7.0/lib64:/usr/local/lib
I tensorflow/stream_executor/cuda/cuda_dnn.cc:1062] Unable to load cuDNN DSO.
"
61,ImportError: No module named core.framework.graph_pb2,"Compiled tensorflow from source, everything works including the eigen value computation example. However, when I try to run the mnist convolutional net example with the command 'python tensorflow/models/image/mnist/convolutional.py' I get the error: ImportError: No module named core.framework.graph_pb2. 
"
59,Error in final step of installation,"Following the instructions at http://tensorflow.org/get_started/os_setup.md#virtualenv_install

The last command for installation is this -- 
""(tensorflow)unknownb8e85638de86:tensorflow jonathanmalkin$ pip install --upgrade <$url_to_binary.whl>""

I get the following response -- 
""-bash: syntax error near unexpected token `newline'""
"
58,No gradient defined for the Reverse op,
57,virtualenv python 2.7.6 import tensorflow. TypeError: __init__() got an unexpected keyword argument 'syntax',"I am running inside a virtual env and followed the given instructions. The following problem is consistent whether I compile from scratch or use the whl from the provided Internet link.

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type ""help"", ""copyright"", ""credits"" or ""license"" for more information.

>>> import tensorflow
Traceback (most recent call last):
  File ""<stdin>"", line 1, in <module>
  File ""/mnt/4tb_internal/python/tensorflow/local/lib/python2.7/site-packages/tensorflow/__init__.py"", line 4, in <module>
    from tensorflow.python import *
  File ""/mnt/4tb_internal/python/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/__init__.py"", line 13, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File ""/mnt/4tb_internal/python/tensorflow/local/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py"", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File ""/mnt/4tb_internal/python/tensorflow/local/lib/python2.7/site-packages/tensorflow/core/framework/attr_value_pb2.py"", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File ""/mnt/4tb_internal/python/tensorflow/local/lib/python2.7/site-packages/tensorflow/core/framework/tensor_pb2.py"", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File ""/mnt/4tb_internal/python/tensorflow/local/lib/python2.7/site-packages/tensorflow/core/framework/tensor_shape_pb2.py"", line 22, in <module>
    serialized_pb=_b('\n,tensorflow/core/framework/tensor_shape.proto\x12\ntensorflow\""d\n\x10TensorShapeProto\x12-\n\x03\x64im\x18\x02 \x03(\x0b\x32 .tensorflow.TensorShapeProto.Dim\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
>>> 
```

Here is the output to `pip show numpy protobuf`

```
Name: numpy
Version: 1.10.1
Location: /mnt/4tb_internal/python/tensorflow/lib/python2.7/site-packages
Requires: 

Name: protobuf
Version: 3.0.0a3
Location: /mnt/4tb_internal/python/tensorflow/lib/python2.7/site-packages
Requires: setuptools
```

Here is the output to `uname -a`. My machine runs Ubuntu 14.04 LTS.

```
Linux yi-2014 3.13.0-64-generic #104-Ubuntu SMP Wed Sep 9 12:36:12 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
"
56,pip error: No such file or directory: '/tmp/pip-...-build/setup.py',"I'm getting the following error when trying to install on a GPU desktop using pip as described in the [tensorflow setup page](http://tensorflow.org/get_started/os_setup.md):

```
$ sudo pip install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
Downloading/unpacking https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
  Downloading tensorflow-0.5.0-cp27-none-linux_x86_64.whl (50.5Mb): 50.5Mb downloaded
  Running setup.py egg_info for package from https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
    Traceback (most recent call last):
      File ""<string>"", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-kYFqUa-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  File ""<string>"", line 14, in <module>
IOError: [Errno 2] No such file or directory: '/tmp/pip-kYFqUa-build/setup.py'
```

See [this Stackoverflow page](http://stackoverflow.com/questions/2204811/pip-install-a-python-package-without-a-setup-py-file) that discusses the problem and indicates that a `setup.py` file is missing in the package.
"
54,Support cuda 7.5 and cudnn 7.0,"Please, add support of cuda 7.5 and cudnn 7.0. 
The best way would be to introduce it as configuration option. Right now, I have to correct everything manually, since only cuda 7.0 and cudnn 6.5 are supported
"
53,Can't install on ubuntu 12.04.5 LTS,"I am running into an error while trying to install tensor flow on Ubuntu.

> $  sudo pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
> 
> Downloading tensorflow-0.5.0-cp27-none-linux_x86_64.whl (10.9Mb): 10.9Mb downloaded
>   Running setup.py egg_info for package from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
>     Traceback (most recent call last):
>       File ""<string>"", line 14, in <module>
>     IOError: [Errno 2] No such file or directory: '/tmp/pip-nulCWJ-build/setup.py'
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
> 
>  File ""<string>"", line 14, in <module>
> 
> IOError: [Errno 2] No such file or directory: '/tmp/pip-nulCWJ-build/setup.py'
> ---
> 
> Command python setup.py egg_info failed with error code 1
"
52,Problem running RNN example,"The shape argument in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/ptb/ptb_word_lm.py#L123 should be a tensor ( [-1] instead of -1). Otherwise, the example does not run.
"
51,Ubuntu ImportError: No module named core.framework.graph_pb2,"I am unable to import tensorflow.
This problem appears whether I try to rebuild from source or by using the .whl directly.

```
(tensorflow)$ uname -a
Linux yi-2014 3.13.0-64-generic #104-Ubuntu SMP Wed Sep 9 12:36:12 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
(tensorflow)$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type ""help"", ""copyright"", ""credits"" or ""license"" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File ""<stdin>"", line 1, in <module>
  File ""tensorflow/__init__.py"", line 4, in <module>
    from tensorflow.python import *
  File ""tensorflow/python/__init__.py"", line 13, in <module>
    from tensorflow.core.framework.graph_pb2 import *
ImportError: No module named core.framework.graph_pb2
>>> 
```
"
50,Ruby API,"`we’re hoping to entice you to contribute SWIG interfaces to your favorite language -- be it Go, Java, Lua, Javascript, or R.` - no Ruby, really? c'mon. Ruby is awesome
"
49,error __init__() got an unexpected keyword argument 'syntax',"I have Ubuntu 14.04 system I installed tensor flow using
pip install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl

then when I try to import tensorflow in my python window, I get the error:
 **init**() got an unexpected keyword argument 'syntax'

Is it a protobuf version problem ?
I have $ protoc --version
libprotoc 2.5.0
"
48,Object Detection,"How do I train and use ImageNet data for Object Detection?

Sid
"
47,Integration with blaze ecosystem numba python to llvm compiler?,"Hi Tensorflow team,

Thanks for the open source work! 

I'm always on the lookout to replace lower level work with python code.   I'm therefore really excited about [Numba](https://github.com/numba/numba) a JIT compiler that can turn a subset of pure python syntax into really fast multithreaded compiled code across multiple backends.  There are also other cool projects that provide different abstractions and graph symbolic representations to different data backends.

http://blaze.pydata.org/
https://github.com/libdynd/dynd-python
https://github.com/blaze/blaze

 I don't have any specific use cases in mind (maybe to efface c++ use?), but just wanted to make the team aware.  As a pydata user, I would love to see any  cooperation and synergy between all these amazing projects in the ecosystem.
"
46,"Missing ""pip install --upgrade pip"" in instructions leads to bogus error ""No such file or directory ... setup.py""","I set up a virtualenv and ran ./bin/activate then tried the install command:

```
(tensorflow) $ ./bin/pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
Downloading/unpacking https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
  Downloading tensorflow-0.5.0-py2-none-any.whl (9.8Mb): 9.8Mb downloaded
  Running setup.py egg_info for package from https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
    Traceback (most recent call last):
      File ""<string>"", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/var/folders/gQ/gQ784XlzFBu-AAhgOvz4Ek+++TI/-Tmp-/pip-emt5Bl-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File ""<string>"", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/var/folders/gQ/gQ784XlzFBu-AAhgOvz4Ek+++TI/-Tmp-/pip-emt5Bl-build/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /var/folders/gQ/gQ784XlzFBu-AAhgOvz4Ek+++TI/-Tmp-/pip-emt5Bl-build
Storing complete log in /Users/munafo/.pip/pip.log
(tensorflow) $ ls -l /var/folders/gQ/gQ784XlzFBu-AAhgOvz4Ek+++TI/-Tmp-/pip-emt5Bl-build/tensorflow/tools/pip_package/setup.py 
-rw-r--r--  1 munafo  staff  2574 Nov  9 17:41 /var/folders/gQ/gQ784XlzFBu-AAhgOvz4Ek+++TI/-Tmp-/pip-emt5Bl-build/tensorflow/tools/pip_package/setup.py
(tensorflow) $
```

As shown in the session, there is no `/var/folders/gQ/gQ784XlzFBu-AAhgOvz4Ek+++TI/-Tmp-/pip-emt5Bl-build/setup.py`, but there is a `/var/folders/gQ/gQ784XlzFBu-AAhgOvz4Ek+++TI/-Tmp-/pip-emt5Bl-build/tensorflow/tools/pip_package/setup.py`

So I suspect pip is failing to interpolate the subdirectory `tensorflow/tools/pip_package` into the path when trying to launch setup.py.

[Here](http://stackoverflow.com/questions/33623453/pip-installation-error-no-such-file-or-directory-setup-py) is another report of the same problem on Linux (the question asker is trying to install tensorflow-0.5.0-cp27-none-linux_x86_64.whl  , and a comment was added by a user who has Ubuntu 12.04)
"
45,OSX PIP Install: Setup.py missing,"I have Python 2.7.4 installed from MacPorts on El Capitan

This seems to be a more fundamental error that the ""six"" dependency.

/var/folders/_1/nd1fyl516b79rmsz9xs3_wsc0000gn/T/pip-2CPCqy-build/setup.py is indeed not there.

```
(tensor)joshuapearce@ZOSIMA:~$ pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
Downloading/unpacking https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
  Downloading tensorflow-0.5.0-py2-none-any.whl (9.8MB): 9.8MB downloaded
  Running setup.py egg_info for package from https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
    Traceback (most recent call last):
      File ""<string>"", line 16, in <module>
    IOError: [Errno 2] No such file or directory: '/var/folders/_1/nd1fyl516b79rmsz9xs3_wsc0000gn/T/pip-2CPCqy-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File ""<string>"", line 16, in <module>

IOError: [Errno 2] No such file or directory: '/var/folders/_1/nd1fyl516b79rmsz9xs3_wsc0000gn/T/pip-2CPCqy-build/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /var/folders/_1/nd1fyl516b79rmsz9xs3_wsc0000gn/T/pip-2CPCqy-build
Storing complete log in /Users/joshuapearce/.pip/pip.log
(tensor)joshuapearce@ZOSIMA:~$ python --version
Python 2.7.4
```
"
44,Can't install on El Capitan - probably python again :(,"Brians-MacBook-Pro:~ brian$ sudo easy_install pip
Searching for pip
Reading https://pypi.python.org/simple/pip/
Best match: pip 7.1.2
Downloading https://pypi.python.org/packages/source/p/pip/pip-7.1.2.tar.gz#md5=3823d2343d9f3aaab21cf9c917710196
Processing pip-7.1.2.tar.gz
Writing /tmp/easy_install-LyZnJ8/pip-7.1.2/setup.cfg
Running pip-7.1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-LyZnJ8/pip-7.1.2/egg-dist-tmp-qbKGmv
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.mailmap'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching 'pip/_vendor/Makefile'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files found matching 'dev-requirements.txt'
no previously-included directories found matching '.travis'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'contrib'
no previously-included directories found matching 'tasks'
no previously-included directories found matching 'tests'
Adding pip 7.1.2 to easy-install.pth file
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Installed /Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip
Brians-MacBook-Pro:~ brian$ pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
Collecting tensorflow==0.5.0 from https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
  Downloading https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl (9.8MB)
    100% |████████████████████████████████| 9.8MB 46kB/s 
Collecting six>=1.10.0 (from tensorflow==0.5.0)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting numpy>=1.9.2 (from tensorflow==0.5.0)
  Downloading numpy-1.10.1-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.7MB)
    100% |████████████████████████████████| 3.7MB 125kB/s 
Installing collected packages: six, numpy, tensorflow
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File ""/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/basecommand.py"", line 211, in main
    status = self.run(options, args)
  File ""/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/commands/install.py"", line 311, in run
    root=options.root_path,
  File ""/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_set.py"", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File ""/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_install.py"", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File ""/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_uninstall.py"", line 125, in remove
    renames(path, new_path)
  File ""/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/utils/**init**.py"", line 315, in renames
    shutil.move(old, new)
  File ""/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py"", line 302, in move
    copy2(src, real_dst)
  File ""/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py"", line 131, in copy2
    copystat(src, dst)
  File ""/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py"", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/ct/f74bny3d10z5nb8n_y5vc6m00000gn/T/pip-BdY92N-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
Brians-MacBook-Pro:~ brian$ 
"
43,Cannot import after installing with pip,"I installed the binary with gpu support from pip, but when I import it, I get this error:

> > > import tensorflow
> > > Traceback (most recent call last):
> > >   File ""<stdin>"", line 1, in <module>
> > >   File ""/home/jxie/anaconda/lib/python2.7/site-packages/tensorflow/**init**.py"", line 4, in <module>
> > >     from tensorflow.python import *
> > >   File ""/home/jxie/anaconda/lib/python2.7/site-packages/tensorflow/python/**init**.py"", line 13, in <module>
> > >     from tensorflow.core.framework.graph_pb2 import *
> > >   File ""/home/jxie/anaconda/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py"", line 8, in <module>
> > >     from google.protobuf import reflection as _reflection
> > >   File ""/home/jxie/anaconda/lib/python2.7/site-packages/google/protobuf/reflection.py"", line 56, in <module>
> > >     from google.protobuf.pyext import cpp_message as message_impl
> > >   File ""/home/jxie/anaconda/lib/python2.7/site-packages/google/protobuf/pyext/cpp_message.py"", line 42, in <module>
> > >     class GeneratedProtocolMessageType(_message.MessageMeta):
> > > AttributeError: 'module' object has no attribute 'MessageMeta'
"
42,Windows support,"I just learned about TensorFlow and I want to install on Windows 7, 64.  I have both Python 2.7 and 3.5  on my PC.  

Thanks,
"
41,Pre-trained models,"One of the successes of Caffe has been its Model Zoo. Are there plans to support importing Caffe models or otherwise provide pre-trained models for TF?
"
40,Error in the Getting started/Variables section of the website,"_**The code part of the code**_
var = tf.Variable(0, name=""counter"")
one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)

_**should be changed to**_

var = tf.Variable(0, name=""counter"")
one = tf.constant(1)
new_value = tf.add(**var**, one)
update = tf.assign(**var**, new_value)

*The rest of the code after this section works as expected *
"
39,is a Python 3 support coming soon ?,
37,Node.js (JavaScript) Wrapper API,"Because JavaScript is Awesome
"
36,No module named tensorflow.python.platform,"when running 
python tensorflow/g3doc/tutorials/mnist/fully_connected_feed.py 

get the following error: 
Traceback (most recent call last):
  File ""tensorflow/g3doc/tutorials/mnist/fully_connected_feed.py"", line 14, in <module>
    import tensorflow.python.platform
ImportError: No module named tensorflow.python.platform
"
35,Can't run TensorBoard on El Captain,"Got this as an issue while trying to run TensorBoard on El Captain.

```
python tensorflow/tensorboard/tensorboard.py
/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'tensorflow/tensorboard/tensorboard.py': [Errno 2] No such file or directory
```

Even after following instructions [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#on-macosx-) for installing tensorflow on a brew based installation of python the error remains same:

```
python tensorflow/tensorboard/tensorboard.py
python: can't open file 'tensorflow/tensorboard/tensorboard.py': [Errno 2] No such file or directory
```
"
34,Error when run docker image on Mac OS X 10.11.1,"I'm getting the following error when trying to execute 
- docker run -it b.gcr.io/tensorflow/tensorflow 

9390232ac080: Error pulling image (latest) from b.gcr.io/tensorflow/tensorflow, endpoint: https://b.gcr.io/v1/, Server error: Status9390232ac080: Error pulling image (latest) from b.gcr.io/tensorflow/tensorflow, Server error: Status 403 while fetching image layer (a5a467fddcb8848a80942d0191134c925fa16ffa9655c540acd34284f4f6375d) 
ac65c371c3a5: Download complete 
a5a467fddcb8: Error pulling dependent layers 

Error pulling image (latest) from b.gcr.io/tensorflow/tensorflow, Server error: Status 403 while fetching image layer (a5a467fddcb8848a80942d0191134c925fa16ffa9655c540acd34284f4f6375d)
"
33,Error while installing tensorflow using pip on Ubuntu 14.04 32-bit system,"Hi devs,

I was trying to install the package in Ubuntu when this error is occurring. I am not sure what the reason is since I am using Python 2.7.6 and already have numpy and six installed. 

```
/usr/local/bin/pip run on Tue Nov 10 12:44:29 2015
tensorflow-0.5.0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.
Exception information:
Traceback (most recent call last):
 File ""/usr/local/lib/python2.7/dist-packages/pip/basecommand.py"", line 122, in main
  status = self.run(options, args)
 File ""/usr/local/lib/python2.7/dist-packages/pip/commands/install.py"", line 257, in run
  InstallRequirement.from_line(name, None))
 File ""/usr/local/lib/python2.7/dist-packages/pip/req.py"", line 167, in from_line
   raise UnsupportedWheel(""%s is not a supported wheel on this platform."" % wheel.filename
UnsupportedWheel: tensorflow-0.5.0-cp27-none-linux_x86_64.whl is not a supported wheel on    this  platform.
```

Apologies if this is a common problem. Thanks in advance :)
"
32,Connectionist Temporal Classification example,"I found these lines in _array_grad.py_

``` python
# Edit Distance has no gradient (but can be used to eval seq2seq or CTC).
ops.NoGradient(""EditDistance"")
```

Is there any implementation of CTC cost function in tensorflow, or any example concern CTC ?
"
31,Slack Channel,"Is there any Slack channel connected to Tensorflow that you could access to get help?
"
30,Go API,"adding a Go port :smile: 
"
29,minimum req: Cuda compute capability 3.5,"Tensorflow seems to require a cuda compute capability of 3.5, thereby excluding amazon G2 instances which use a GRID K520 with 3.0, might be good to know:

```
tensorflow/core/common_runtime/gpu/gpu_init.cc:88] Found device 0 with properties:
name: GRID K520
major: 3 minor: 0 memoryClockRate (GHz) 0.797
pciBusID 0000:00:03.0
Total memory: 4.00GiB
Free memory: 3.95GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:112] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:122] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:611] Ignoring gpu device (device: 0, name: GRID K520, pci bus id: 0000:00:03.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:611] Ignoring gpu device (device: 0, name: GRID K520, pci bus id: 0000:00:03.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:611] Ignoring gpu device (device: 0, name: GRID K520, pci bus id: 0000:00:03.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
```
"
28,Could port to OpenCL?,"Could the project be port to OpenCL? Currently it only supports CUDA which is proprietary. OpenCL can be more wide spread and portable.
"
27,Warning while creating Session on Mac OS X: can't determine number of CPU cores,"While creating a Session, I get this warning (using pre-built whl on OSX). Any ideas?

```
s = tf.Session()
can't determine number of CPU cores: assuming 4
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 4
can't determine number of CPU cores: assuming 4
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 4
```
"
26,simplify contributing process,"Currently the contributing process is rather complex... I have to use another website, clone the repo, and more. I'm just interested in making some minor tweaks to the documentation that normally can be done with just a few clicks using GitHub.
"
25,Cuda 3.0?,"Are there plans to support Cuda compute capability 3.0? 
"
24,"Problems running the image example (Python 2.7.10, PyEnv, Xubuntu 14.04 64bit)","JFYI, I'm getting the following error when trying to execute the models/image/mnist/convolutional.py example (Python 2.7.10 in PyEnv, on Xubuntu 14.04, 64bit):

``` bash
[samuel site-packages]$ pwd
/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages
[samuel site-packages]$ python tensorflow/models/image/mnist/convolutional.py
Traceback (most recent call last):
  File ""tensorflow/models/image/mnist/convolutional.py"", line 12, in <module>
    import tensorflow.python.platform
  File ""/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/__init__.py"", line 4, in <module>
    from tensorflow.python import *
  File ""/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/python/__init__.py"", line 22, in <module>
    from tensorflow.python.client.client_lib import *
  File ""/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/python/client/client_lib.py"", line 35, in <module>
    from tensorflow.python.client.session import InteractiveSession
  File ""/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/python/client/session.py"", line 11, in <module>
    from tensorflow.python import pywrap_tensorflow as tf_session
  File ""/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py"", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File ""/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py"", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: PyUnicodeUCS4_FromStringAndSize
```

Will see if I can figure out something, but thought to report in the meanwhile.
"
23,Distributed Version,"Is there any distributed version of TensorFlow that could work on multiple machines?

-Minjie
"
22,OpenCL support,"I understand TensorFlow only supports CUDA. What would need to be done to add in OpenCL support?
"
21,GPU_Base dockerfile image not found,"I'm attempting to use the GPU dockerfile to build an image with gpu support, however it points at b.gcr.io/tensorflow-testing/tensorflow-full which doesn't appear to be accessible. The image at b.gcr.io/tensorflow/tensorflow-full doesn't have CUDA in it, is there a different image I need to point the script at?
"
20,CUDA 7.5 fails with pip install and docker (Ubuntu 14.04),"Installing via:

``` bash
# For GPU-enabled version (only install this version if you have the CUDA sdk installed)
$ pip install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
```

Tried to run the alexnet_benchmark.py and it's looking for CUDA 7.0 specifically.

I have CUDA 7.5 on my machine.

Full stack:

``` bash
Traceback (most recent call last):
  File ""alexnet_benchmark.py"", line 21, in <module>
    import tensorflow.python.platform
  File ""/home/awesomebox/anaconda/lib/python2.7/site-packages/tensorflow/__init__.py"", line 4, in <module>
    from tensorflow.python import *
  File ""/home/awesomebox/anaconda/lib/python2.7/site-packages/tensorflow/python/__init__.py"", line 22, in <module>
    from tensorflow.python.client.client_lib import *
  File ""/home/awesomebox/anaconda/lib/python2.7/site-packages/tensorflow/python/client/client_lib.py"", line 35, in <module>
    from tensorflow.python.client.session import InteractiveSession
  File ""/home/awesomebox/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py"", line 11, in <module>
    from tensorflow.python import pywrap_tensorflow as tf_session
  File ""/home/awesomebox/anaconda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py"", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File ""/home/awesomebox/anaconda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py"", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: libcudart.so.7.0: cannot open shared object file: No such file or directory
```

Tried the docker install, but the docker image is configured for a particular NVIDIA driver version, and doesn't work with others. (this is a known issue: docker driver version and system driver version must exactly match)
"
19,Swift API,"Swift is a very popular and expressive language with a large community of pro developers.
"
18,C# api,"C# is very popular and expressive language with a large community of pro developers.
"
17,Windows Support and Documentation,"I was excited to see tensorflow, but as many other users, we are on Windows, would be nice to see this support happen. Will you accept Windows port contributions?

In the meantime, Microsoft recently released their Deep Learning toolkit which scales on multiple machines with GPUs for both Linux and Windows. https://github.com/Microsoft/CNTK
"
16,iOS Support and Example,"Currently there is [an example on Android](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android) but no corresponding IOS example even though the white paper calls out both Android and IOS.
"
15,Quantized ops?,"In the data types section, there are `quantized ops`
http://tensorflow.org/resources/dims_types.md#data_types

Found a note here:
https://github.com/tensorflow/tensorflow/blob/d6357a5849db980df51d00d8a9ff874cda2faeb3/tensorflow/cc/ops/const_op.h#L65

Can you explain what these are?
"
14,g3doc format,"Has the g3doc specification been publicly released?  Is an effort going to be made so that outside contributors know exactly how comments should be written in order to be correctly parsed?
"
12,Remote worker configuration,"Does this release support remote workers out of the box?  I couldn't find details in the tutorials, but the whitepaper and `tensorflow/core/common_runtime/device.h` talked about adding remote devices through RPC.  Is a parameter server or alternative already implemented in here somewhere?  If remote workers are supported out of the box, what is the execution model?  Is there a daemon or do you have to configure a session in a certain way to act as one?
"
11,0.5.0 wheel install on Mac OS X using Homebrew python broken,"This is what happens:

``` bash
~: pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
Collecting tensorflow==0.5.0 from https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
  Downloading https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl (9.8MB)
    100% |████████████████████████████████| 9.8MB 51kB/s
Collecting six>=1.10.0 (from tensorflow==0.5.0)
  Downloading six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.9.2 in /usr/local/lib/python2.7/site-packages (from tensorflow==0.5.0)
Installing collected packages: six, tensorflow
  Found existing installation: six 1.9.0
    Uninstalling six-1.9.0:
      Successfully uninstalled six-1.9.0
Successfully installed six-1.10.0 tensorflow-0.5.0
~: python
Python 2.7.10 (default, Jul 13 2015, 12:05:58)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type ""help"", ""copyright"", ""credits"" or ""license"" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File ""<stdin>"", line 1, in <module>
  File ""/usr/local/lib/python2.7/site-packages/tensorflow/__init__.py"", line 4, in <module>
    from tensorflow.python import *
  File ""/usr/local/lib/python2.7/site-packages/tensorflow/python/__init__.py"", line 13, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File ""/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py"", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File ""/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/attr_value_pb2.py"", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File ""/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/tensor_pb2.py"", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File ""/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/tensor_shape_pb2.py"", line 22, in <module>
    serialized_pb=_b('\n,tensorflow/core/framework/tensor_shape.proto\x12\ntensorflow\""d\n\x10TensorShapeProto\x12-\n\x03\x64im\x18\x02 \x03(\x0b\x32 .tensorflow.TensorShapeProto.Dim\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```
"
10,Go API,"Hi!,
I'm really interested on contribute in my spare time on this project, it  would be great for me port the Python libraries to Go, or help with this task, the problem is that after read the ""Contributing guidelines"" I still don't know how to do it.
I tried to sing the Individual CLA, but I get an error that says: ""You must be an owner of the contributors group in order to submit this CLA."".

Btw, are you working, or do you plan to implement soon the Go libs?

Some related projects that I implemented in Go: https://github.com/alonsovidales/pit - This is a distributed recommender system based in the ""Adaptive Bootstrapping of Recommender Systems Using Decision Trees"" paper by Yahoo. The site of the project: http://pitia.info/
And the Go ML: Some machine learning algorithms in Go: https://github.com/alonsovidales/go_ml I also implemented Neural Networks with CUDA: https://github.com/alonsovidales/go_ml/tree/cuda_implementation

Thanks,
"
9,Typo in getting started guide,"http://tensorflow.org/get_started/basic_usage.md#variables

In the code example, 1 is being added to ""counter"", which is named ""var"" initially, but referred to as ""state"" later. My guess is that these are meant to refer to the same thing, and a typo in one of the variable names made it into the example code.
"
8,Setting lower gcc version for cuda,"gcc 4.10 and up are not supported for the required cuda toolkit.  How can I specify a different version of gcc to bazel?  I tried setting a new version with --compiler, but it reported that no toolchain was found.  Do I need to provide a CROSSTOOL file or is there an easier way?
"
7,API docs does not list RNNs,"https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/nn.md

(It has convolutional layers listed, for instance, but does not show the RNNs. Actually, I don't quite see anything corresponding to a fully-connected layer either)
"
6,Pre-trained models,"Is there any plan to include caffe-like pre-trained models to use for predictions?
"
5,Java interface,"Issue to trace effort of swig interface for java. Started implementation - will update with progress. If anyone has any comments/tips - please feel welcome to join the discussion!
"
4,Installation over pip fails to import with protobuf 2.6.1,"Pip freeze reports the following protobuf version

```
protobuf==2.6.1
```

However, upon importing I get the following error

```
Traceback (most recent call last):
  File ""/home/panmari/PycharmProjects/tensor_stuff/stuff.py"", line 150, in <module>
    import tensorflow as tf
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py"", line 4, in <module>
    from tensorflow.python import *
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py"", line 13, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/graph_pb2.py"", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/attr_value_pb2.py"", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/tensor_pb2.py"", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/tensor_shape_pb2.py"", line 22, in <module>
    serialized_pb=_b('\n,tensorflow/core/framework/tensor_shape.proto\x12\ntensorflow\""d\n\x10TensorShapeProto\x12-\n\x03\x64im\x18\x02 \x03(\x0b\x32 .tensorflow.TensorShapeProto.Dim\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

Do I need a newer version of the protobuf package?
"
3,"JVM, .NET Language Support","Your website says ""... contribute SWIG interfaces to your favorite language ..."". It will be good if yo have pure implementations in other languages like JVM and .NET without having to use SWIG.
"
2,"OSX Yosemite ""can't determine number of CPU cores: assuming 4""","``` python
>>> import tensorflow as tf
>>> hello = tf.constant('hello, tensorflow')
>>> sess = tf.Session()
can't determine number of CPU cores: assuming 4
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 4
can't determine number of CPU cores: assuming 4
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 4
```

got this warning but still works though
"
1,Add support for Python 3.x,"Currently we only support Python 2.7, but we should support Python 3.
"
linux_x86_64.whl is not a supported wheel on    this  platform.,,
```,,
Apologies if this is a common problem. Thanks in advance :),,
"
32,Connectionist Temporal Classification example,I found these lines in _array_grad.py_",,
``` python,,
# Edit Distance has no gradient (but can be used to eval seq2seq or CTC).,,
"ops.NoGradient(""""EditDistance"""")",,
```,,
Is there any implementation of CTC cost function in tensorflow, or any example concern CTC ?,
"
31,Slack Channel,Is there any Slack channel connected to Tensorflow that you could access to get help?",,
"
30,Go API,adding a Go port :smile: ",,
"
29,minimum req: Cuda compute capability 3.5,Tensorflow seems to require a cuda compute capability of 3.5", thereby excluding amazon G2 instances which use a GRID K520 with 3.0, might be good to know:
```,,
tensorflow/core/common_runtime/gpu/gpu_init.cc:88] Found device 0 with properties:,,
name: GRID K520,,
major: 3 minor: 0 memoryClockRate (GHz) 0.797,,
pciBusID 0000:00:03.0,,
Total memory: 4.00GiB,,
Free memory: 3.95GiB,,
I tensorflow/core/common_runtime/gpu/gpu_init.cc:112] DMA: 0,,
I tensorflow/core/common_runtime/gpu/gpu_init.cc:122] 0:   Y,,
I tensorflow/core/common_runtime/gpu/gpu_device.cc:611] Ignoring gpu device (device: 0, name: GRID K520, pci bus id: 0000:00:03.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:611] Ignoring gpu device (device: 0, name: GRID K520, pci bus id: 0000:00:03.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:611] Ignoring gpu device (device: 0, name: GRID K520, pci bus id: 0000:00:03.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
```,,
"
28,Could port to OpenCL?,Could the project be port to OpenCL? Currently it only supports CUDA which is proprietary. OpenCL can be more wide spread and portable.",,
"
27,Warning while creating Session on Mac OS X: can't determine number of CPU cores,While creating a Session", I get this warning (using pre-built whl on OSX). Any ideas?,
```,,
s = tf.Session(),,
can't determine number of CPU cores: assuming 4,,
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 4,,
can't determine number of CPU cores: assuming 4,,
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 4,,
```,,
"
26,simplify contributing process,Currently the contributing process is rather complex... I have to use another website", clone the repo, and more. I'm just interested in making some minor tweaks to the documentation that normally can be done with just a few clicks using GitHub.
"
25,Cuda 3.0?,Are there plans to support Cuda compute capability 3.0? ",,
